const bancoPreguntas = [
    { pregunta: "1. Según el texto, conducir no es solo encender el vehículo porque también requiere:", opciones: ["Solo habilidad física", "Conocimientos de normas y factores de seguridad vial", "Saber cambiar marchas", "Saber mecánica avanzada"], correcta: 1 },
    { pregunta: "2. El objetivo general del tema es:", opciones: ["Aprender a manejar vehículos pesados", "Comprender movilidad y conducción segura en Costa Rica", "Memorizar señales de tránsito", "Reducir el uso del transporte público"], correcta: 1 },
    { pregunta: "3. Conducir debe desarrollarse dentro de un marco de:", opciones: ["Competencia y rapidez", "Respeto mutuo, tolerancia y protección de la vida", "Prioridad solo para automóviles", "Libertad sin normas"], correcta: 1 },
    { pregunta: "4. ¿Cuál de los siguientes NO se menciona como usuario del sistema vial?", opciones: ["Peatones", "Ciclistas", "Conductores de autobuses", "Pilotos de avión"], correcta: 3 },
    { pregunta: "5. Un conductor novato se considera novato durante:", opciones: ["1 año", "2 años", "3 años", "5 años"], correcta: 2 },
    { pregunta: "6. El conductor profesional se caracteriza por:", opciones: ["Tener licencia A1 únicamente", "Conducir como actividad laboral principal", "Renovar licencia cada 6 meses", "No necesitar acreditación"], correcta: 1 },
    { pregunta: "7. El “conductor común” (no tipificado) es quien:", opciones: ["Tiene menos de 3 años de licencia", "Es profesional acreditado", "Tiene más de 3 años de licencia y no es profesional", "No tiene licencia"], correcta: 2 },
    { pregunta: "8. Conductor no acreditado es:", opciones: ["Quien tiene licencia vigente", "Quien no cuenta con el tipo de licencia correspondiente", "Quien conduce taxi", "Quien conduce bicicleta"], correcta: 1 },
    { pregunta: "9. La movilidad es fundamental porque permite:", opciones: ["Solo recreación", "Solo trabajo", "Desplazamiento por trabajo, estudio, recreación y acceso a servicios", "Únicamente transporte privado"], correcta: 2 },
    { pregunta: "10. El enfoque de “sistema seguro” reconoce que:", opciones: ["El conductor nunca se equivoca", "La seguridad depende solo del vehículo", "El ser humano puede cometer errores y el sistema debe reducir consecuencias", "Solo se necesita más policía"], correcta: 2 },
    { pregunta: "11. Una acción incluida en el “sistema seguro” es:", opciones: ["Infraestructura vial segura", "Aumentar velocidad en autopistas", "Quitar ciclovías", "Reducir semáforos"], correcta: 0 },
    { pregunta: "12. ¿Cuál es una de las cinco acciones del sistema seguro?", opciones: ["Menos controles policiales", "Mejor asistencia a las víctimas", "Más vehículos sin mantenimiento", "Menos educación vial"], correcta: 1 },
    { pregunta: "13. El ejemplo de movilidad sostenible menciona como mejora:", opciones: ["Más presas", "Carriles exclusivos para bicicletas y semáforos peatonales adecuados", "Menos señalización", "Más adelantamientos"], correcta: 1 },
    { pregunta: "14. Un factor de riesgo se define como:", opciones: ["Algo que elimina accidentes", "Condición que aumenta la probabilidad de accidente y lesiones graves", "Solo una multa", "Una señal de tránsito"], correcta: 1 },
    { pregunta: "15. Los factores de riesgo pueden relacionarse con:", opciones: ["Carretera, vehículo, conducta del conductor y atención post accidente", "Solo la carretera", "Solo el conductor", "Solo el clima"], correcta: 0 },
    { pregunta: "16. Según la OMS, “exposición al riesgo” incluye:", opciones: ["Consumo de alcohol", "Distancias de traslado y falta de aceras/ciclovías", "No usar casco", "Atención postraumática"], correcta: 1 },
    { pregunta: "17. “Posibilidad de que ocurra un accidente” incluye:", opciones: ["Retrasos en la detección", "Mal estado de carreteras y distracción", "Rehabilitación", "Diseño de la vía"], correcta: 1 },
    { pregunta: "18. “Gravedad de las lesiones” se relaciona con:", opciones: ["Falta de servicios de emergencia", "No usar cinturón/casco/SRI y diseño de la vía", "Volumen de tránsito", "Distancias de traslado"], correcta: 1 },
    { pregunta: "19. “Evolución de las lesiones después del accidente” incluye:", opciones: ["No usar casco", "Exceso de velocidad", "Traslado al centro médico y atención postraumática", "Tipo de vehículo"], correcta: 2 },
    { pregunta: "20. Un accidente de tránsito, según el texto, es:", opciones: ["Un acto intencional siempre", "Una acción culposa con muerte, lesiones o daños materiales por infracción", "Un daño sin infracción", "Un evento solo material sin ley"], correcta: 1 },
    { pregunta: "21. Colisión es:", opciones: ["Volcar el carro", "Choque entre vehículos o contra objeto fijo", "Golpear peatón", "Salirse a la cuneta sin daño"], correcta: 1 },
    { pregunta: "22. Vuelco ocurre cuando:", opciones: ["Se frena suave", "El vehículo pierde estabilidad y se voltea", "Se cambia de carril", "Se estaciona mal"], correcta: 1 },
    { pregunta: "23. Atropello es:", opciones: ["Choque contra pared", "Golpear a una persona o animal con un vehículo", "Choque trasero", "Cambio de carril"], correcta: 1 },
    { pregunta: "24. Choque de frente suele ocurrir por:", opciones: ["Mantener distancia", "Invadir carril contrario por adelantamiento indebido", "Usar cinturón", "Bajar velocidad"], correcta: 1 },
    { pregunta: "25. Colisión trasera se relaciona principalmente con:", opciones: ["Buen mantenimiento", "No guardar distancia, distracción o exceso de velocidad", "Señalización adecuada", "Carril exclusivo"], correcta: 1 },
    { pregunta: "26. Colisión lateral ocurre generalmente por:", opciones: ["Frenar en recta", "Giro o cambio de carril", "Manejar en reversa 1 km", "Usar luces bajas"], correcta: 1 },
    { pregunta: "27. La DAM (Declaración de Accidente Menor) aplica cuando hay:", opciones: ["Heridos", "Solo daños materiales sin personas heridas", "Choque con muerte", "Daños a peatones"], correcta: 1 },
    { pregunta: "28. La DAM busca:", opciones: ["Aumentar congestión", "Resolver ágilmente y evitar presas", "Evitar reportes", "Sustituir a emergencias médicas"], correcta: 1 },
    { pregunta: "29. En el caso de Julián, un factor de riesgo de la vía fue:", opciones: ["Neumáticos desgastados", "Baches y falta de señalización", "Cinturón puesto", "Motor nuevo"], correcta: 1 },
    { pregunta: "30. En el caso de Julián, un factor de riesgo del vehículo fue:", opciones: ["Lluvia", "Neumáticos muy desgastados", "Baches", "Ambulancia cerca"], correcta: 1 },
    { pregunta: "31. En el caso de Julián, la conducta riesgosa fue:", opciones: ["Ir a 80 km/h en lluvia y baja visibilidad", "Reducir velocidad", "Detenerse a revisar llantas", "No adelantar"], correcta: 0 },
    { pregunta: "32. Una acción que pudo prevenir el accidente fue:", opciones: ["Aumentar velocidad para pasar rápido", "Reducir velocidad en lluvia", "Ignorar baches", "Quitar cinturón"], correcta: 1 },
    { pregunta: "33. Una consecuencia del accidente en el caso fue:", opciones: ["Sin daños", "Contusiones y daños materiales", "Solo multa", "Mejoró la visibilidad"], correcta: 1 },
    { pregunta: "34. Después de un accidente se debe:", opciones: ["Irse sin avisar", "Solicitar ayuda, asegurar zona y reportar según corresponda", "Discutir con otros conductores", "Bloquear la vía"], correcta: 1 },
    { pregunta: "35. Vehículos motorizados se desplazan por:", opciones: ["Fuerza humana", "Motor eléctrico/híbrido/gasolina/diésel", "Tracción animal", "Empuje manual"], correcta: 1 },
    { pregunta: "36. Vehículos no motorizados incluyen:", opciones: ["Camiones", "Trenes", "Bicicletas y triciclos no motorizados", "Autobuses"], correcta: 2 },
    { pregunta: "37. Ciclovías son:", opciones: ["Exclusivas para carros", "Destinadas al tránsito de bicicletas y triciclos no motorizados", "Para estacionar", "Solo para motos"], correcta: 1 },
    { pregunta: "38. Aceras son:", opciones: ["Para vehículos", "Exclusivas para peatones", "Para bicicletas", "Para camiones"], correcta: 1 },
    { pregunta: "39. Espaldón es:", opciones: ["Carril rápido", "Sección contigua a la calzada para emergencias/peatones/estacionamiento según condiciones", "Zona exclusiva buses", "Ciclovía"], correcta: 1 },
    { pregunta: "40. Cuneta o sistema de drenaje permite:", opciones: ["Mayor velocidad", "Flujo de agua de lluvia en carretera", "Cambiar carriles", "Estacionar buses"], correcta: 1 },
    { pregunta: "41. Carreteras primarias:", opciones: ["Son senderos", "Soportan alto tránsito y conectan puntos importantes", "Solo en zonas rurales", "No conectan ciudades"], correcta: 1 },
    { pregunta: "42. Calles locales son:", opciones: ["Fuera del área urbana", "Dentro del cuadrante de un área urbana", "Caminos de herradura", "Carreteras primarias"], correcta: 1 },
    { pregunta: "43. Caminos vecinales sirven para:", opciones: ["Conectar rutas primarias", "Acceso a fincas, haciendas, pueblos o centros poblados", "Solo autopistas", "Solo bicicletas"], correcta: 1 },
    { pregunta: "44. En Costa Rica, la edad mínima general para obtener licencia es:", opciones: ["16", "17", "18", "21"], correcta: 2 },
    { pregunta: "45. La excepción de edad mínima mencionada es para:", opciones: ["B-1 a los 16", "A1 a los 16", "B-2 a los 16", "D a los 16"], correcta: 1 },
    { pregunta: "46. Un requisito para obtener licencia clase B es:", opciones: ["No saber leer ni escribir", "Aprobar curso teórico de educación vial", "Tener 15 años", "No presentar dictamen médico"], correcta: 1 },
    { pregunta: "47. El Permiso Temporal de Aprendizaje tiene vigencia de:", opciones: ["1 mes", "2 meses", "3 meses", "6 meses"], correcta: 2 },
    { pregunta: "48. Para permiso temporal, el aspirante debe conducir:", opciones: ["Solo, siempre", "Acompañado por persona con licencia del mismo tipo o superior, vigente, con 5 años o más", "Con cualquier amigo", "Solo de noche"], correcta: 1 },
    { pregunta: "49. Para la prueba práctica, debe presentarse:", opciones: ["5 minutos antes", "10 minutos antes", "30 minutos antes", "1 hora después"], correcta: 2 },
    { pregunta: "50. La regla de los 3 segundos sirve para:", opciones: ["Medir velocidad máxima", "Calcular distancia segura entre vehículos", "Saber cuándo usar bocina", "Cambiar de carril sin señalizar"], correcta: 1 },
    { pregunta: "51. La señalización en la vía es fundamental principalmente para:", opciones: ["Aumentar la velocidad", "La seguridad al conducir", "Reducir el uso de ciclovías", "Evitar que haya peatones"], correcta: 1 },
    { pregunta: "52. Estudiar el significado de cada señal ayuda a:", opciones: ["Evitar accidentes y multas", "Manejar sin licencia", "Saltarse semáforos", "No usar cinturón"], correcta: 0 },
    { pregunta: "53. El objetivo general del tema es:", opciones: ["Memorizar nombres de calles", "Diferenciar señales según función y clasificación para conducir seguro", "Aprender mecánica", "Conducir solo en autopista"], correcta: 1 },
    { pregunta: "54. Un objetivo específico es:", opciones: ["Ignorar señales horizontales", "Identificar señales y su significado", "Conducir sin normas", "Acelerar en zonas escolares"], correcta: 1 },
    { pregunta: "55. Las señales de tránsito son:", opciones: ["Sugerencias sin obligación", "Normas que ordenan la vía y regulan conducta", "Solo dibujos decorativos", "Exclusivas para conductores"], correcta: 1 },
    { pregunta: "56. Además de obligación legal, las señales también son:", opciones: ["Un gasto", "Una responsabilidad personal", "Un permiso opcional", "Una advertencia solo para peatones"], correcta: 1 },
    { pregunta: "57. Las señales funcionan como un sistema de:", opciones: ["Publicidad", "Comunicación", "Entretenimiento", "Competencia"], correcta: 1 },
    { pregunta: "58. Las señales nos informan sobre todo, EXCEPTO:", opciones: ["Prioridades", "Riesgos", "Condiciones de la vía", "Marca de llantas"], correcta: 3 },
    { pregunta: "59. Las señales de reglamentación indican:", opciones: ["Lugares turísticos", "Obligaciones, prohibiciones o restricciones", "Solo servicios", "Solo obras"], correcta: 1 },
    { pregunta: "60. Las señales de reglamentación generalmente son:", opciones: ["Triangulares y rojas", "Circulares, fondo blanco con borde rojo", "Rectangulares verdes", "Rombo amarillo"], correcta: 1 },
    { pregunta: "61. Ejemplo de señal de reglamentación:", opciones: ["Hospital", "Curva peligrosa", "ALTO", "Derrumbe"], correcta: 2 },
    { pregunta: "62. Las señales de reglamentación son:", opciones: ["Opcionales", "De cumplimiento obligatorio", "Solo para ciclistas", "Solo de noche"], correcta: 1 },
    { pregunta: "63. Las señales de prevención sirven para:", opciones: ["Prohibir estacionar", "Advertir peligros reales o potenciales", "Indicar hoteles", "Marcar carriles de buses"], correcta: 1 },
    { pregunta: "64. Las señales de prevención generalmente son:", opciones: ["Fondo amarillo y forma rombo", "Fondo blanco circular", "Fondo verde rectangular", "Fondo azul circular"], correcta: 0 },
    { pregunta: "65. Ejemplo de señal de prevención:", opciones: ["No parquear", "Zona escolar", "Gasolinera", "Nombre de calle"], correcta: 1 },
    { pregunta: "66. Las señales de prevención alertan para:", opciones: ["Acelerar", "Reducir velocidad y estar atentos", "Adelantar sin mirar", "Ignorar el riesgo"], correcta: 1 },
    { pregunta: "67. Las señales de información sirven para:", opciones: ["Prohibir giros", "Orientar y guiar al conductor", "Advertir derrumbes", "Indicar multas"], correcta: 1 },
    { pregunta: "68. Ejemplo de señal informativa:", opciones: ["Hotel", "Curva peligrosa", "Prohibido girar", "Reductor de velocidad"], correcta: 0 },
    { pregunta: "69. Las señales horizontales son:", opciones: ["Solo semáforos", "Marcas pintadas en el pavimento", "Solo rótulos verticales", "Sirenas"], correcta: 1 },
    { pregunta: "70. La línea amarilla separa:", opciones: ["Carriles del mismo sentido", "Sentidos opuestos de circulación", "Zonas de parqueo", "Ciclovías"], correcta: 1 },
    { pregunta: "71. Línea amarilla continua significa:", opciones: ["Sí se puede adelantar siempre", "No se puede adelantar", "Solo adelantar motos", "Se puede adelantar de noche"], correcta: 1 },
    { pregunta: "72. Línea amarilla discontinua significa:", opciones: ["No se puede adelantar nunca", "Sí se puede adelantar si es seguro", "Prohíbe girar", "Obliga a parar"], correcta: 1 },
    { pregunta: "73. La línea blanca separa:", opciones: ["Sentidos opuestos", "Carriles del mismo sentido", "Ciclovía y acera", "Zona escolar y hospital"], correcta: 1 },
    { pregunta: "74. La línea de parada indica:", opciones: ["Dónde acelerar", "Dónde detenerse en ALTO o CEDA", "Dónde adelantar", "Dónde tocar bocina"], correcta: 1 },
    { pregunta: "75. La “cebra” (zona peatonal) sirve para:", opciones: ["Estacionar", "Proteger el paso de peatones", "Adelantar buses", "Marcar carril reversible"], correcta: 1 },
    { pregunta: "76. La zona de estacionamiento sirve para:", opciones: ["Delimitar espacios para parquear", "Separar sentidos opuestos", "Indicar hospital", "Prohibir buses"], correcta: 0 },
    { pregunta: "77. El color verde en demarcación se usa para:", opciones: ["Carriles compartidos con ciclistas", "Prohibido girar", "Ceda el paso", "Zona de buses"], correcta: 0 },
    { pregunta: "78. El color azul en demarcación indica:", opciones: ["Zonas de carga", "Espacios para personas con discapacidad", "Carril reversible", "Línea de parada"], correcta: 1 },
    { pregunta: "79. La canalización se usa para:", opciones: ["Guiar el flujo vehicular en intersecciones complejas", "Indicar hoteles", "Prohibir semáforos", "Marcar ciclovía solo con blanco"], correcta: 0 },
    { pregunta: "80. El carril central de giro izquierdo:", opciones: ["Se usa para adelantar", "Permite girar a la izquierda con seguridad", "Es exclusivo de buses", "Se usa como parqueo"], correcta: 1 },
    { pregunta: "81. El carril exclusivo para buses es:", opciones: ["Para todos los vehículos", "Solo para transporte público", "Para bicicletas", "Para motos únicamente"], correcta: 1 },
    { pregunta: "82. El carril reversible se usa para:", opciones: ["Aumentar multas", "Descongestionar zonas conflictivas", "Evitar semáforos", "Sustituir ciclovías"], correcta: 1 },
    { pregunta: "83. El carril reversible funciona:", opciones: ["Siempre igual", "Por horarios", "Solo en zonas rurales", "Solo de noche"], correcta: 1 },
    { pregunta: "84. La caja amarilla (cajón) indica:", opciones: ["Adelantar en intersección", "Prohibido bloquear intersecciones", "Zona de estacionamiento", "Zona escolar"], correcta: 1 },
    { pregunta: "85. ¿Qué se debe evitar con la caja amarilla?", opciones: ["Girar a la izquierda", "Quedarse detenido dentro si no se puede salir", "Usar direccional", "Bajar velocidad"], correcta: 1 },
    { pregunta: "86. La ciclovía es:", opciones: ["Carril exclusivo para bicicletas", "Carril exclusivo buses", "Zona de carga", "Vía peatonal"], correcta: 0 },
    { pregunta: "87. Según el texto, la ciclovía se marca en color:", opciones: ["Amarillo", "Blanco", "Azul", "Naranja"], correcta: 1 },
    { pregunta: "88. Los reductores de velocidad se colocan para:", opciones: ["Obligar a aumentar velocidad", "Obligar a disminuir velocidad", "Indicar destinos", "Marcar parqueos"], correcta: 1 },
    { pregunta: "89. Un tipo de reductor de velocidad es:", opciones: ["Semáforo peatonal", "Lomo de burro", "Línea blanca", "Señal informativa"], correcta: 1 },
    { pregunta: "90. El paso peatonal elevado busca:", opciones: ["Proteger zonas sensibles", "Quitar señalización", "Aumentar el tráfico", "Mejorar adelantamientos"], correcta: 0 },
    { pregunta: "91. En semáforo vehicular, rojo significa:", opciones: ["Avanzar", "Detenerse", "Acelerar", "Rebasar"], correcta: 1 },
    { pregunta: "92. En semáforo vehicular, amarillo indica:", opciones: ["Precaución / detenerse", "Avanzar siempre", "No pase", "Carril reversible"], correcta: 0 },
    { pregunta: "93. En semáforo vehicular, verde significa:", opciones: ["Detenerse", "Precaución", "Avanzar", "No pase"], correcta: 2 },
    { pregunta: "94. En semáforo peatonal, rojo significa:", opciones: ["Puede cruzar", "No pase", "Adelante rápido", "Cruce por la ciclovía"], correcta: 1 },
    { pregunta: "95. En semáforo peatonal, verde significa:", opciones: ["No pase", "Puede cruzar", "Solo bicicletas", "Solo buses"], correcta: 1 },
    { pregunta: "96. Una señal luminosa transitoria indica:", opciones: ["Nombre de calles", "Trabajos, emergencias o desvíos", "Prohibido parquear", "Curva peligrosa fija"], correcta: 1 },
    { pregunta: "97. El señalamiento sonoro incluye:", opciones: ["Líneas amarillas", "Sirenas de emergencia", "Cajas amarillas", "Ciclovías"], correcta: 1 },
    { pregunta: "98. El señalamiento manual lo realizan:", opciones: ["Conductores particulares", "Oficiales de tránsito", "Peatones", "Pasajeros"], correcta: 1 },
    { pregunta: "99. En autopista, la velocidad mínima indicada en el texto es:", opciones: ["25 km/h", "50 km/h", "60 km/h", "80 km/h"], correcta: 1 },
    { pregunta: "100. En zona escolar u hospital, el máximo indicado es:", opciones: ["25 km/h", "40 km/h", "50 km/h", "60 km/h"], correcta: 0 },
    { pregunta: "101. Conducir de forma segura implica, entre otros, principalmente:", opciones: ["Manejar solo de día", "Conocer el funcionamiento del vehículo y darle mantenimiento preventivo", "Usar únicamente transmisión automática", "Conducir siempre rápido"], correcta: 1 },
    { pregunta: "102. Un conductor que conoce su vehículo:", opciones: ["Reduce el riesgo de accidentes", "No necesita señales", "Nunca se equivoca", "Puede ignorar el mantenimiento"], correcta: 0 },
    { pregunta: "103. El objetivo general del tema es:", opciones: ["Aprender a cambiar llantas sin herramientas", "Reconocer mandos y controles del vehículo para minimizar accidentes", "Memorizar marcas de carros", "Conducir en autopista únicamente"], correcta: 1 },
    { pregunta: "104. Los mandos y controles del automóvil incluyen:", opciones: ["Solo frenos y llantas", "Indicadores del panel, visibilidad, llantas, frenos, transmisiones y mantenimiento", "Solo aire acondicionado", "Solo radio y pantalla"], correcta: 1 },
    { pregunta: "105. En las luces del panel, el color rojo significa:", opciones: ["Información activa", "Atención inmediata (peligro)", "Revisar pronto", "Señal de mantenimiento normal"], correcta: 1 },
    { pregunta: "106. En el panel, el color amarillo/ámbar indica:", opciones: ["Detenerse siempre", "Revisar pronto", "Direccionales activas", "Que todo está normal"], correcta: 1 },
    { pregunta: "107. En el panel, el color verde suele indicar:", opciones: ["Peligro", "Información activa (ej. direccionales)", "Falla grave", "Sobrecalentamiento"], correcta: 1 },
    { pregunta: "108. El tacómetro indica:", opciones: ["Kilómetros recorridos", "Revoluciones del motor (RPM)", "Nivel de combustible", "Temperatura externa"], correcta: 1 },
    { pregunta: "109. El tacómetro ayuda a:", opciones: ["Evitar forzar el motor", "Saber la presión de llantas", "Medir el aceite", "Encender direccionales"], correcta: 0 },
    { pregunta: "110. Cuando el combustible baja mucho, suele:", opciones: ["Apagarse el motor de inmediato", "Encenderse una luz de advertencia", "Encenderse la luz verde", "Sonar la bocina"], correcta: 1 },
    { pregunta: "111. Si el motor está sobrecalentado, el texto indica:", opciones: ["Acelerar para enfriar", "Detenerse inmediatamente", "Abrir el radiador en caliente", "Continuar si no hay humo"], correcta: 1 },
    { pregunta: "112. ¿Qué NO se debe hacer nunca con el radiador?", opciones: ["Revisarlo en frío", "Abrirlo en caliente", "Mantenerlo cerrado", "Revisar temperatura"], correcta: 1 },
    { pregunta: "113. Si la luz de batería/alternador permanece encendida:", opciones: ["Indica direccionales", "Puede haber falla en la carga de batería", "Indica nivel de aceite alto", "Indica ABS activo"], correcta: 1 },
    { pregunta: "114. El velocímetro muestra:", opciones: ["RPM del motor", "Velocidad en km/h", "Kilómetros totales de vida del carro", "Presión de llantas"], correcta: 1 },
    { pregunta: "115. El velocímetro sirve para:", opciones: ["Respetar límites legales", "Medir desgaste de llanta", "Encender luces", "Abrir el radiador"], correcta: 0 },
    { pregunta: "116. El odómetro indica:", opciones: ["Nivel de gasolina", "Kilómetros recorridos", "Temperatura del motor", "Potencia del motor"], correcta: 1 },
    { pregunta: "117. El odómetro es útil para:", opciones: ["Mantenimiento y control", "Cambiar a reversa", "Regular direccionales", "Evitar puntos ciegos"], correcta: 0 },
    { pregunta: "118. El indicador de freno de mano activado significa:", opciones: ["Que el ABS falló", "Que el freno está puesto", "Que las puertas están abiertas", "Que falta aceite"], correcta: 1 },
    { pregunta: "119. La luz de puertas abiertas indica que:", opciones: ["Falta combustible", "Alguna puerta, capó o maletero está abierto", "Hay fallo en airbag", "El motor está frío"], correcta: 1 },
    { pregunta: "120. El indicador del cinturón de seguridad significa que:", opciones: ["Todos lo llevan puesto", "Un ocupante no lo lleva puesto", "Falló el ABS", "Hay combustible en reserva"], correcta: 1 },
    { pregunta: "121. La luz de airbag encendida indica:", opciones: ["Direccionales activas", "Falla en el sistema de bolsas de aire", "Que está en modo deportivo", "Luces altas activas"], correcta: 1 },
    { pregunta: "122. ¿Cuál es una luz del vehículo mencionada en el texto?", opciones: ["Luz de posición", "Luz de neón interior obligatoria", "Luz violeta de emergencia", "Luz de “turbo”"], correcta: 0 },
    { pregunta: "123. En transmisión automática, “P” significa:", opciones: ["Pista", "Parqueo", "Potencia", "Pase"], correcta: 1 },
    { pregunta: "124. En transmisión automática, “R” significa:", opciones: ["Rodaje", "Reversa", "Rendimiento", "Ruta"], correcta: 1 },
    { pregunta: "125. En transmisión automática, “D” significa:", opciones: ["Detener", "Avance", "Descanso", "Derrape"], correcta: 1 },
    { pregunta: "126. “L/L1” en automática se usa para:", opciones: ["Mayor fuerza (subidas)", "Retroceso rápido", "Apagar motor", "Activar ABS"], correcta: 0 },
    { pregunta: "127. “S” en automática indica:", opciones: ["Seguro", "Deportivo", "Suspensión", "Señal"], correcta: 1 },
    { pregunta: "128. Según el texto, NO se debe cambiar a P o R:", opciones: ["Con el vehículo detenido", "Con el vehículo en movimiento", "Con el freno de mano", "En subidas"], correcta: 1 },
    { pregunta: "129. La señal de “aceite bajo” puede:", opciones: ["Mejorar el motor", "Causar daños graves al motor", "Encender direccionales", "Aumentar presión de llantas"], correcta: 1 },
    { pregunta: "130. La temperatura alta del motor indica:", opciones: ["Enfriamiento normal", "Sobrecalentamiento; detenerse", "Batería baja", "ABS activo"], correcta: 1 },
    { pregunta: "131. El nivel bajo de combustible indica que:", opciones: ["Está en reserva", "Está lleno", "No hay marchamo", "Falló el alternador"], correcta: 0 },
    { pregunta: "132. “Check Engine” intermitente puede indicar:", opciones: ["Falla leve", "Falla grave siempre", "Aire en llantas", "Puerta abierta"], correcta: 0 },
    { pregunta: "133. “Check Engine” permanente puede indicar:", opciones: ["Información activa", "Falla grave", "Direccional activada", "Estacionamiento correcto"], correcta: 1 },
    { pregunta: "134. Si la luz del ABS queda encendida:", opciones: ["El ABS funciona perfecto", "El sistema antibloqueo puede no funcionar correctamente", "Indica luz baja activa", "Indica gasolina llena"], correcta: 1 },
    { pregunta: "135. El limpia parabrisas permite:", opciones: ["Aumentar velocidad", "Limpiar lluvia, polvo y suciedad", "Medir RPM", "Enfriar motor"], correcta: 1 },
    { pregunta: "136. Los vidrios y ventanas deben:", opciones: ["Tener obstrucciones para el sol", "No tener obstrucciones", "Usarse solo de noche", "Abrirse siempre"], correcta: 1 },
    { pregunta: "137. El espejo central:", opciones: ["Solo sirve para ver el costado", "Permite ver detrás y es ajustable", "Elimina todos los puntos ciegos", "Se ajusta con el vehículo en movimiento"], correcta: 1 },
    { pregunta: "138. Los espejos laterales:", opciones: ["Reducen puntos ciegos y amplían campo visual", "Solo son decorativos", "Reemplazan el parabrisas", "Se ajustan por los pasajeros"], correcta: 0 },
    { pregunta: "139. El espejo “ojo de pescado” sirve para:", opciones: ["Aumentar el ruido", "Ampliar visión lateral y reducir punto ciego", "Medir velocidad", "Enfriar frenos"], correcta: 1 },
    { pregunta: "140. La cámara de retroceso:", opciones: ["Se activa en reversa", "Se activa solo en D", "Se usa para luces altas", "Solo funciona en autopista"], correcta: 0 },
    { pregunta: "141. Los espejos y cámaras deben ajustarse:", opciones: ["Durante la conducción", "Antes de iniciar el viaje", "Por los pasajeros", "En movimiento y sin detenerse"], correcta: 1 },
    { pregunta: "142. Los espejos deben ajustarse solo cuando:", opciones: ["El carro está detenido", "Va a 60 km/h", "Hay neblina", "Hay lluvia"], correcta: 0 },
    { pregunta: "143. Los puntos ciegos son:", opciones: ["Zonas que se ven perfectamente con espejos", "Zonas que el conductor no ve desde su asiento ni con espejos", "Zonas exclusivas de ciclovías", "Zonas que solo existen de noche"], correcta: 1 },
    { pregunta: "144. Los puntos ciegos son peligrosos porque:", opciones: ["Mejoran visibilidad", "Ocultan peatones, ciclistas, motociclistas o vehículos", "Reducen accidentes", "Aumentan estabilidad del carro"], correcta: 1 },
    { pregunta: "145. Un método para reducir puntos ciegos es:", opciones: ["No usar espejos", "Girar la cabeza y observar antes de maniobrar", "Acelerar para salir rápido", "Manejar solo por el carril izquierdo"], correcta: 1 },
    { pregunta: "146. Según el texto, las tecnologías ADAS:", opciones: ["Eliminan por completo los puntos ciegos", "Alertan con sensores sobre vehículos en puntos ciegos", "Son solo decorativas", "Sustituyen al conductor"], correcta: 1 },
    { pregunta: "147. Aunque existan ayudas, los puntos ciegos:", opciones: ["Se eliminan totalmente", "No se eliminan por completo; hay que conducir con precaución", "Solo existen en motos", "Solo existen en reversa"], correcta: 1 },
    { pregunta: "148. Las luces del vehículo deben servir para:", opciones: ["Ver, ser visto y alertar", "Solo decorar", "Solo iluminar la placa", "Solo encender en autopista"], correcta: 0 },
    { pregunta: "149. La luz alta (larga) ilumina aproximadamente:", opciones: ["30 metros", "100 metros", "10 metros", "200 metros"], correcta: 1 },
    { pregunta: "150. Las luces bajas son obligatorias, según el texto:", opciones: ["De 6:00 a.m. a 6:00 p.m.", "De 6:00 p.m. a 6:00 a.m.", "Solo en lluvia", "Solo en autopista"], correcta: 1 },
    { pregunta: "151. El objetivo general del tema de maniobras es:", opciones: ["Aprender mecánica básica", "Fomentar habilidades para maniobras seguras en carretera", "Manejar solo en ciudad", "Evitar usar direccionales"], correcta: 1 },
    { pregunta: "152. Un objetivo específico del tema es:", opciones: ["Reconocer procedimientos correctos para adelantamientos y frenados", "Manejar sin retrovisores", "Aumentar velocidad en curvas", "Estacionar solo en puentes"], correcta: 0 },
    { pregunta: "153. Al conducir, siempre realizamos maniobras para:", opciones: ["Avanzar, detenernos, girar y esquivar obstáculos", "Solo acelerar", "Solo frenar", "Solo estacionar"], correcta: 0 },
    { pregunta: "154. Un momento clave para maniobras es:", opciones: ["Solo durante la conducción", "Antes de conducir, durante y finalización del viaje", "Solo al final del viaje", "Solo al arrancar"], correcta: 1 },
    { pregunta: "155. La postura correcta del conductor incluye:", opciones: ["Espalda encorvada para ver mejor", "Espalda recta y postura cómoda", "Rodillas totalmente estiradas", "Pedales lejos para mayor fuerza"], correcta: 1 },
    { pregunta: "156. Las rodillas deben estar:", opciones: ["Totalmente estiradas", "Ligeramente flexionadas", "Pegadas al volante", "Cruzadas"], correcta: 1 },
    { pregunta: "157. La distancia mínima recomendada entre pecho y volante es:", opciones: ["5 cm", "10 cm", "20 cm", "40 cm"], correcta: 2 },
    { pregunta: "158. La inclinación del asiento debe ser:", opciones: ["Totalmente hacia atrás", "Ligeramente reclinado", "Totalmente vertical sin ajuste", "Inclinado hacia adelante"], correcta: 1 },
    { pregunta: "159. Un asiento demasiado reclinado es negativo porque:", opciones: ["Mejora el control", "Se pierde control del vehículo", "Aumenta visibilidad"], correcta: 1 },
    { pregunta: "160. El apoyacabezas debe ubicarse:", opciones: ["A la altura del cuello", "A la altura de las orejas", "Bajo la nuca", "En la espalda"], correcta: 1 },
    { pregunta: "161. La función del apoyacabezas es:", opciones: ["Mejorar velocidad", "Prevenir lesiones cervicales en choques", "Activar airbag", "Reducir consumo"], correcta: 1 },
    { pregunta: "162. El cinturón de seguridad debe colocarse:", opciones: ["Después de salir a carretera", "Antes de iniciar la marcha", "Solo si hay policía", "Solo en autopista"], correcta: 1 },
    { pregunta: "163. La banda horizontal del cinturón va sobre:", opciones: ["Abdomen", "Pelvis", "Pecho", "Cuello"], correcta: 1 },
    { pregunta: "164. La banda diagonal del cinturón va sobre:", opciones: ["Clavícula y pecho", "Abdomen", "Cadera únicamente", "Cuello"], correcta: 0 },
    { pregunta: "165. El cinturón NUNCA debe colocarse:", opciones: ["Sobre la clavícula", "Debajo del brazo", "Sobre la pelvis", "Sobre el pecho"], correcta: 1 },
    { pregunta: "166. En embarazadas, la banda baja del cinturón debe ir:", opciones: ["Sobre el abdomen", "Baja sobre la pelvis, no sobre el abdomen", "En el cuello", "Suelta para comodidad"], correcta: 1 },
    { pregunta: "167. En niños, el texto indica usar:", opciones: ["Cinturón debajo del brazo", "Silla adecuada según edad y peso", "Solo el asiento delantero", "Nada si es trayecto corto"], correcta: 1 },
    { pregunta: "168. Según el texto, el cinturón es:", opciones: ["Un hábito secundario", "El principal hábito de seguridad", "Útil solo en choques leves", "Solo para el conductor"], correcta: 1 },
    { pregunta: "169. Los retrovisores deben ajustarse:", opciones: ["Mientras se conduce", "Antes de arrancar", "Solo por el pasajero", "Solo si hay lluvia"], correcta: 1 },
    { pregunta: "170. Ajustar retrovisores ayuda a:", opciones: ["Aumentar consumo de gasolina", "Eliminar puntos ciegos y anticipar riesgos", "Hacer adelantamientos sin revisar", "Manejar sin direccionales"], correcta: 1 },
    { pregunta: "171. Antes de salir, es importante conocer:", opciones: ["Solo la radio", "Ubicación de pedales, palanca, luces, direccionales y emergencia", "Solo el aire acondicionado", "Solo el GPS"], correcta: 1 },
    { pregunta: "172. Si es un vehículo que no conoce, debe:", opciones: ["Salir de una vez", "Verificar todo antes de salir", "Acelerar más para adaptarse", "Ajustar espejos en movimiento"], correcta: 1 },
    { pregunta: "173. Antes de arrancar se debe revisar:", opciones: ["Solo el lado izquierdo", "Adelante, atrás y lados", "Solo atrás", "Solo el tablero"], correcta: 1 },
    { pregunta: "174. La revisión del entorno busca confirmar que no haya cerca:", opciones: ["Solo autos", "Niños, peatones o animales", "Solo señales", "Semáforos"], correcta: 1 },
    { pregunta: "175. La sujeción del volante recomendada es:", opciones: ["“2 y 2”", "“10 y 10”", "“6 y 6”", "Con una mano siempre"], correcta: 1 },
    { pregunta: "176. La posición “10 y 10” permite:", opciones: ["Menor control", "Mejor control y reacción rápida", "Solo comodidad", "Frenar más lento"], correcta: 1 },
    { pregunta: "177. Al iniciar la marcha se recomienda:", opciones: ["Salir acelerando fuerte", "Iniciar suave y progresivamente, a baja velocidad", "Iniciar en velocidad alta", "Salir sin revisar entorno"], correcta: 1 },
    { pregunta: "178. En salida en pendiente hacia arriba se recomienda:", opciones: ["No usar freno de mano", "Freno de mano activado y soltar progresivamente", "Solo reversa", "Acelerar al máximo"], correcta: 1 },
    { pregunta: "179. En salida en pendiente hacia abajo se recomienda:", opciones: ["Primera marcha y control del freno", "Neutro para bajar fácil", "Acelerar fuerte", "Apagar el motor"], correcta: 0 },
    { pregunta: "180. Ingresar al flujo vehicular es riesgoso porque:", opciones: ["No se usan espejos", "Es una de las maniobras más riesgosas del manejo", "Siempre hay semáforo", "Solo pasan buses"], correcta: 1 },
    { pregunta: "181. Para ingresar al flujo vehicular, se debe:", opciones: ["Entrar obligando a otros a frenar", "Ingresar sin obligar a otros a frenar bruscamente", "No revisar ciclistas", "No calcular velocidades"], correcta: 1 },
    { pregunta: "182. Antes de adelantar, se debe verificar:", opciones: ["Que haya línea continua", "Zona permitida y buena visibilidad", "Que haya rotonda", "Que sea puente"], correcta: 1 },
    { pregunta: "183. Antes de adelantar, NO debe hacerse en:", opciones: ["Rectas con visibilidad", "Puentes, intersecciones o pasos peatonales", "Zonas permitidas", "Carretera despejada"], correcta: 1 },
    { pregunta: "184. Antes de adelantar se debe revisar:", opciones: ["Solo el velocímetro", "Retrovisores y ángulo muerto", "Solo el asiento", "Solo el tablero"], correcta: 1 },
    { pregunta: "185. Antes de adelantar, se debe activar:", opciones: ["Direccional derecha", "Direccional izquierda", "Luces de emergencia", "Luz alta fija"], correcta: 1 },
    { pregunta: "186. Durante el adelantamiento se recomienda:", opciones: ["Manejo lento y largo", "Maniobra rápida y segura, con ambas manos al volante", "Apagar direccional", "Invadir carril contrario el mayor tiempo posible"], correcta: 1 },
    { pregunta: "187. Después de adelantar, se debe:", opciones: ["Quedarse en carril izquierdo siempre", "Señalizar regreso al carril derecho", "Frenar fuerte de inmediato", "Apagar luces"], correcta: 1 },
    { pregunta: "188. Después de adelantar, se debe mantener:", opciones: ["Distancia segura con el vehículo adelantado", "Cero distancia para avanzar", "Distancia solo si llueve", "Distancia solo con buses"], correcta: 0 },
    { pregunta: "189. Para adelantar motocicletas o bicicletas, se debe mantener mínimo:", opciones: ["0.50 m", "1.00 m", "1.50 m", "2.50 m"], correcta: 2 },
    { pregunta: "190. Está prohibido adelantar cuando hay:", opciones: ["Línea amarilla o blanca continua", "Línea discontinua siempre", "Zona amplia y recta", "Buena visibilidad"], correcta: 0 },
    { pregunta: "191. Está prohibido adelantar dentro de:", opciones: ["Rectas", "Rotonda", "Autopista", "Calle local"], correcta: 1 },
    { pregunta: "192. Está prohibido adelantar con:", opciones: ["Buena visibilidad", "Neblina o lluvia intensa", "Carretera seca", "Poca circulación"], correcta: 1 },
    { pregunta: "193. Si el vehículo delantero ya va al límite de velocidad:", opciones: ["Debe adelantar igual", "No se debe adelantar", "Se acelera sin mirar", "Se adelanta en curva"], correcta: 1 },
    { pregunta: "194. Si un vehículo en sentido contrario invade su carril adelantando, usted debe:", opciones: ["Mantener velocidad y esperar", "Disminuir velocidad y advertir con luces", "Acelerar para ganar", "Cambiarse al carril contrario"], correcta: 1 },
    { pregunta: "195. Si es necesario para evitar choque con un vehículo invasor, se recomienda:", opciones: ["Nunca frenar", "Orillarse o detenerse completamente si hace falta", "Tocar bocina y seguir", "Acelerar siempre"], correcta: 1 },
    { pregunta: "196. Maniobras que NO son adelantamiento (por obstáculos) requieren:", opciones: ["No usar direccional", "Verificar carril contrario libre y usar direccional", "Adelantar sin revisar", "Pasar rápido sin mirar"], correcta: 1 },
    { pregunta: "197. Si no puede esquivar el obstáculo de forma segura, debe:", opciones: ["Acelerar fuerte", "Detenerse y encender luces de emergencia", "Invadir carril contrario igual", "Apagar luces"], correcta: 1 },
    { pregunta: "198. La reversa se usa:", opciones: ["Siempre en autopista", "Solo en casos necesarios (estacionar o fuerza mayor)", "Para adelantar", "En curvas"], correcta: 1 },
    { pregunta: "199. En reversa, la velocidad debe ser:", opciones: ["Alta para terminar rápido", "Muy baja (máx. 20 km/h)", "60 km/h", "30 km/h"], correcta: 1 },
    { pregunta: "200. Nunca se debe usar reversa en:", opciones: ["Estacionamientos", "Autopistas, curvas, túneles o puentes", "Calles residenciales", "Lugares permitidos"], correcta: 1 },
    { pregunta: "201. La seguridad vial es fundamental principalmente para:", opciones: ["Aumentar el flujo vehicular", "Proteger la vida de conductores, pasajeros y peatones", "Reducir la cantidad de vehículos", "Evitar el uso de cinturón"], correcta: 1 },
    { pregunta: "202. Según el texto, a mayor cantidad de vehículos:", opciones: ["Menor riesgo", "Mayor riesgo", "No cambia el riesgo", "Solo cambia en autopistas"], correcta: 1 },
    { pregunta: "203. Un accidente puede deberse a:", opciones: ["Condiciones climáticas adversas", "Distracciones", "Mal estado del vehículo", "Todas las anteriores"], correcta: 3 },
    { pregunta: "204. La clave para reducir accidentes es:", opciones: ["Acelerar más", "Identificar riesgos y aplicar medidas preventivas", "Conducir solo de día", "Evitar puentes siempre"], correcta: 1 },
    { pregunta: "205. La conducción segura depende de:", opciones: ["Atención constante, velocidad adecuada, control emocional y vehículo en buen estado", "Solo velocidad alta", "Solo experiencia", "Solo frenos nuevos"], correcta: 0 },
    { pregunta: "206. Una zona de mayor riesgo mencionada es:", opciones: ["Parqueos bajo techo", "Curvas cerradas", "Calles con semáforos nuevos", "Zonas con aceras amplias"], correcta: 1 },
    { pregunta: "207. La seguridad pasiva del vehículo se refiere a:", opciones: ["Dispositivos que protegen en caso de accidente", "Sistemas de entretenimiento", "Luces de lujo", "Aumento de potencia"], correcta: 0 },
    { pregunta: "208. Un ejemplo de seguridad pasiva es:", opciones: ["Radio", "Cinturón de seguridad", "GPS", "Aire acondicionado"], correcta: 1 },
    { pregunta: "209. La seguridad pasiva busca principalmente:", opciones: ["Aumentar velocidad", "Reducir la gravedad de lesiones", "Evitar multas", "Mejorar consumo de combustible"], correcta: 1 },
    { pregunta: "210. El cinturón debe ajustarse de manera que la banda superior vaya:", opciones: ["En el cuello", "Sobre el hombro", "Bajo el brazo", "Sobre el abdomen"], correcta: 1 },
    { pregunta: "211. La banda inferior del cinturón debe ir:", opciones: ["Sobre el abdomen", "Sobre la cadera", "En el cuello", "En el brazo"], correcta: 1 },
    { pregunta: "212. Es incorrecto con el cinturón:", opciones: ["Ajustarlo correctamente", "Pasarlo bajo el brazo", "Colocarlo sobre el hombro", "Colocarlo sobre la cadera"], correcta: 1 },
    { pregunta: "213. Según el texto, NUNCA se debe:", opciones: ["Usar cinturón", "Llevar niños en las rodillas", "Ajustar el cinturón", "Usar SRI"], correcta: 1 },
    { pregunta: "214. El cinturón reduce el riesgo de:", opciones: ["Solo multas", "Lesiones graves y muerte", "Solo cansancio", "Solo derrapes"], correcta: 1 },
    { pregunta: "215. El airbag:", opciones: ["Reemplaza el cinturón", "Complementa al cinturón", "Se activa en lluvia", "Se activa al frenar suave"], correcta: 1 },
    { pregunta: "216. El airbag se activa principalmente en:", opciones: ["Impacto frontal", "Viento fuerte", "Frenado normal", "Giro a la izquierda"], correcta: 0 },
    { pregunta: "217. Niños menores de 13 años no deben viajar adelante con:", opciones: ["Ventanas cerradas", "Airbag activado", "Cinturón bien puesto", "Música baja"], correcta: 1 },
    { pregunta: "218. El lugar más seguro para menores de 13 años es:", opciones: ["Asiento delantero", "Asiento trasero", "En las rodillas", "En el asiento del conductor"], correcta: 1 },
    { pregunta: "219. El sistema de retención infantil debe elegirse según:", opciones: ["Color de la silla", "Peso y estatura (no solo edad)", "Marca del carro", "Distancia del viaje"], correcta: 1 },
    { pregunta: "220. Los SRI deben estar:", opciones: ["Sueltos para comodidad", "Homologados y bien instalados", "Solo en viajes largos", "Solo si hay policía"], correcta: 1 },
    { pregunta: "221. El chasis y carrocería están diseñados para:", opciones: ["Aumentar el ruido", "Absorber energía del impacto", "Aumentar la velocidad", "Reducir gasolina"], correcta: 1 },
    { pregunta: "222. Los cristales de seguridad se fragmentan en:", opciones: ["Pedazos grandes", "Pequeños trozos para evitar cortaduras graves", "Láminas filosas", "Polvo"], correcta: 1 },
    { pregunta: "223. Ante condiciones inesperadas, el texto recomienda:", opciones: ["Distracción controlada", "Máxima atención y ajustar velocidad según clima y entorno", "Acelerar para pasar rápido", "Conducir sin luces"], correcta: 1 },
    { pregunta: "224. En lluvia, un riesgo mencionado es:", opciones: ["Mayor adherencia", "Menor adherencia", "Mejor visibilidad", "Menos aceite en la vía"], correcta: 1 },
    { pregunta: "225. En lluvia, una consecuencia puede ser:", opciones: ["Derrapes", "Mayor control", "Más adherencia", "Mayor estabilidad siempre"], correcta: 0 },
    { pregunta: "226. En lluvia, se recomienda:", opciones: ["Aumentar velocidad", "Reducir velocidad y aumentar distancia", "No usar luces", "Frenar bruscamente"], correcta: 1 },
    { pregunta: "227. En niebla, la recomendación es:", opciones: ["Usar luces altas", "Usar luces bajas", "Apagar luces", "Acelerar"], correcta: 1 },
    { pregunta: "228. En viento fuerte, se recomienda:", opciones: ["Soltar el volante para estabilizar", "Sujetar firme el volante y disminuir velocidad", "Frenar brusco siempre", "Girar con rapidez"], correcta: 1 },
    { pregunta: "229. En sol intenso, un riesgo es:", opciones: ["Mejor atención", "Encandilamiento y somnolencia", "Más adherencia", "Menor fatiga"], correcta: 1 },
    { pregunta: "230. En sol intenso, se recomienda:", opciones: ["No usar lentes", "Usar lentes con protección UV", "Acelerar más", "Conducir sin pausas"], correcta: 1 },
    { pregunta: "231. El hidroplaneamiento es:", opciones: ["Frenar sobre seco", "Pérdida de contacto llanta–pavimento", "Exceso de aire en llantas", "Salida en pendiente"], correcta: 1 },
    { pregunta: "232. Para evitar riesgos en hidroplaneamiento, se recomienda:", opciones: ["Frenar bruscamente", "Sujetar firme el volante y disminuir velocidad", "Cambiar a reversa", "Acelerar para salir"], correcta: 1 },
    { pregunta: "233. Sobre la carga del vehículo, se recomienda:", opciones: ["Llevar objetos sueltos en asientos", "Guardar todo en el maletero", "Poner objetos en el tablero", "Llevar cajas en el regazo"], correcta: 1 },
    { pregunta: "234. En un impacto, los objetos sueltos pueden:", opciones: ["Hacerse más livianos", "Convertirse en proyectiles", "Pegarse al piso", "Desaparecer"], correcta: 1 },
    { pregunta: "235. El uso del celular al conducir puede causar:", opciones: ["Menor tiempo de reacción", "Mayor tiempo de reacción y posible invasión de carril", "Mejor visualización", "Mayor concentración"], correcta: 1 },
    { pregunta: "236. Una recomendación sobre el celular es:", opciones: ["Usarlo en semáforo verde", "Usarlo solo detenido", "Usarlo con una mano", "Usarlo en curvas"], correcta: 1 },
    { pregunta: "237. Manipular música al conducir puede provocar:", opciones: ["Mayor atención", "Apartar la vista y distraer manos del volante", "Mejor control", "Menos riesgo"], correcta: 1 },
    { pregunta: "238. Sobre música, se recomienda:", opciones: ["Elegirla antes de iniciar y volumen moderado", "Cambiar canciones en curvas", "Subir volumen al máximo", "Manipular pantalla mientras maneja"], correcta: 0 },
    { pregunta: "239. Con pasajeros (amigos/compañeros), se debe:", opciones: ["Permitir distracciones", "Evitar conductas que distraigan al conductor", "Quitar cinturón", "Aumentar velocidad"], correcta: 1 },
    { pregunta: "240. Discutir durante el viaje puede:", opciones: ["Aumentar concentración", "Hacer que el conductor pierda concentración", "Mejorar reflejos", "Evitar accidentes"], correcta: 1 },
    { pregunta: "241. En viajes con menores, se recomienda:", opciones: ["Atenderlos mientras conduce", "No atender necesidades del menor mientras conduce", "Llevarlos en rodillas", "No usar SRI"], correcta: 1 },
    { pregunta: "242. Con mascotas, se recomienda:", opciones: ["Llevarlas sueltas", "Transportarlas en dispositivos especiales", "Llevarlas en el regazo del conductor", "Que se muevan libremente"], correcta: 1 },
    { pregunta: "243. La fatiga reduce:", opciones: ["El consumo de combustible", "La atención y coordinación", "La necesidad de descanso", "La distancia de frenado"], correcta: 1 },
    { pregunta: "244. Una recomendación ante somnolencia es:", opciones: ["Seguir manejando para llegar rápido", "Detenerse si siente sueño", "Tomar más riesgos", "No hacer pausas"], correcta: 1 },
    { pregunta: "245. El estrés y la ira pueden generar:", opciones: ["Conducción más calmada", "Reacciones agresivas e impulsividad", "Mejor control del volante", "Mayor paciencia siempre"], correcta: 1 },
    { pregunta: "246. Para manejar estrés/ira se recomienda:", opciones: ["Reaccionar ante provocaciones", "Mantener calma y controlar emociones", "Aumentar velocidad", "Competir con otros"], correcta: 1 },
    { pregunta: "247. Alcohol y drogas afectan:", opciones: ["Solo la vista", "Reflejos, coordinación y percepción del riesgo", "Solo el oído", "Solo el GPS"], correcta: 1 },
    { pregunta: "248. El consumo de alcohol/drogas puede provocar:", opciones: ["Solo advertencias", "Multas, suspensión de licencia y hasta cárcel", "Ninguna consecuencia", "Solo cursos"], correcta: 1 },
    { pregunta: "249. Algunos medicamentos pueden causar:", opciones: ["Mejor concentración", "Somnolencia, mareos, confusión y problemas de visión", "Más reflejos", "Menos riesgo"], correcta: 1 },
    { pregunta: "250. Si un medicamento produce efectos secundarios, el texto indica:", opciones: ["Conducir más despacio y ya", "No conducir", "Conducir igual", "Conducir solo de noche"], correcta: 1 },
    { pregunta: "251. ¿Cuál es el propósito principal de las normas de tránsito?", opciones: ["Recaudar dinero mediante multas", "Proteger la vida y regular la movilidad", "Limitar el uso de vehículos", "Favorecer a conductores profesionales"], correcta: 1 },
    { pregunta: "252. La Ley de Tránsito por Vías Públicas Terrestres y Seguridad Vial regula principalmente:", opciones: ["La compra y venta de vehículos", "La circulación de vehículos y conductas en la vía pública", "El precio del combustible", "El mantenimiento mecánico"], correcta: 1 },
    { pregunta: "253. ¿Cuál de las siguientes conductas corresponde a una infracción categoría A?", opciones: ["No usar luces reglamentarias", "Uso del teléfono celular al conducir", "Conducir bajo influencia del alcohol", "No usar direccional"], correcta: 2 },
    { pregunta: "254. Una infracción categoría A acumula:", opciones: ["2 puntos", "4 puntos", "6 puntos", "No acumula puntos"], correcta: 2 },
    { pregunta: "255. ¿Cuál conducta corresponde a categoría B?", opciones: ["Competencias ilegales", "No usar dispositivo de seguridad para menores", "Placas falsas", "Exceso de velocidad extremo"], correcta: 1 },
    { pregunta: "256. El uso del teléfono celular mientras se conduce genera:", opciones: ["Advertencia verbal", "4 puntos en la licencia", "6 puntos en la licencia", "Suspensión inmediata sin proceso"], correcta: 1 },
    { pregunta: "257. Conducir a velocidades extremadamente altas puede considerarse:", opciones: ["Falta leve", "Conducción temeraria", "Error administrativo", "Infracción sin puntos"], correcta: 1 },
    { pregunta: "258. La conducción temeraria puede generar:", opciones: ["Solo multa económica", "Arresto inmediato", "Solo curso obligatorio", "Advertencia sin registro"], correcta: 1 },
    { pregunta: "259. Participar en competencias ilegales en la vía pública constituye:", opciones: ["Infracción categoría B", "Conducción preventiva", "Conducción temeraria", "Falta sin sanción"], correcta: 2 },
    { pregunta: "260. Si una persona acumula todos los puntos permitidos en su licencia:", opciones: ["Se se le elimina la multa", "Se suspende el derecho a conducir", "Debe pagar doble marchamo", "Solo recibe advertencia"], correcta: 1 },
    { pregunta: "261. Para reducir puntos acumulados, una opción es:", opciones: ["Cambiar de vehículo", "Realizar curso de educación vial", "No pagar la multa", "Presentar recurso automático"], correcta: 1 },
    { pregunta: "262. Si una persona reincide en pérdida total de puntos:", opciones: ["Se se le eliminan automáticamente", "La suspensión puede ser más prolongada", "No hay consecuencia adicional", "Solo paga multa económica"], correcta: 1 },
    { pregunta: "263. “Ceder el paso” significa:", opciones: ["Acelerar primero", "Permitir prioridad a quien corresponde", "Detenerse siempre", "Ignorar señalización"], correcta: 1 },
    { pregunta: "264. Una sanción administrativa puede incluir:", opciones: ["Pena de prisión", "Multa o suspensión de licencia", "Arresto inmediato", "Detención de 96 horas"], correcta: 1 },
    { pregunta: "265. Una sanción penal puede incluir:", opciones: ["Trabajo comunitario voluntario", "Multa leve", "Cárcel", "Advertencia escrita"], correcta: 2 },
    { pregunta: "266. No ceder el paso a peatones es:", opciones: ["Conducta permitida en zona urbana", "Conducta de riesgo sancionable", "Solo falta moral", "Recomendación opcional"], correcta: 1 },
    { pregunta: "267. Alterar o falsificar placas del vehículo constituye:", opciones: ["Falta sin puntos", "Conducta de alto riesgo sancionable", "Advertencia administrativa", "Infracción sin multa"], correcta: 1 },
    { pregunta: "268. Conducir bajo efectos del alcohol afecta principalmente:", opciones: ["Solo la velocidad", "Reflejos y capacidad de decisión", "Solo la vista", "Solo la audición"], correcta: 1 },
    { pregunta: "269. El sistema de puntos tiene como finalidad:", opciones: ["Castigar económicamente", "Corregir conductas del conductor", "Quitar licencias permanentemente", "Aumentar multas"], correcta: 1 },
    { pregunta: "270. En caso de recibir una boleta, el conductor puede:", opciones: ["Ignorarla", "Pagarla o impugnarla conforme al procedimiento legal", "Romperla", "Transferirla a otra persona"], correcta: 1 },
    { pregunta: "271. Un conductor es detenido por circular con placas alteradas. Esta conducta se clasifica como:", opciones: ["Infracción sin puntos", "Infracción categoría B", "Conducta de alto riesgo (categoría A)", "Advertencia verbal"], correcta: 2 },
    { pregunta: "272. Un conductor no respeta una señal de alto. Esta conducta genera:", opciones: ["6 puntos", "4 puntos", "No genera puntos", "Suspensión inmediata automática"], correcta: 1 },
    { pregunta: "273. Conducir bajo influencia del alcohol puede generar:", opciones: ["Solo multa económica", "Multa y puntos", "Proceso penal y posible detención", "Solo curso obligatorio"], correcta: 2 },
    { pregunta: "274. Si un conductor participa en competencias ilegales en la vía pública, puede enfrentar:", opciones: ["Multa leve", "Arresto inmediato y proceso judicial", "Solo suspensión temporal", "Solo acumulación de puntos"], correcta: 1 },
    { pregunta: "275. El sistema de puntos en la licencia busca principalmente:", opciones: ["Incrementar sanciones económicas", "Controlar y corregir conductas peligrosas", "Quitar licencias sin previo aviso", "Sancionar únicamente a conductores novatos"], correcta: 1 },
    { pregunta: "276. Un conductor acumula el máximo de puntos permitidos. ¿Qué ocurre?", opciones: ["Recibe advertencia escrita", "Se suspende su derecho a conducir", "Debe pagar doble multa", "Pierde el marchamo"], correcta: 1 },
    { pregunta: "277. Para recuperar puntos acumulados, el conductor puede:", opciones: ["Ignorar la infracción", "Realizar curso de educación vial o trabajo comunitario", "Renovar la licencia inmediatamente", "Cambiar de categoría de licencia"], correcta: 1 },
    { pregunta: "278. Si un conductor reincide y vuelve a perder todos los puntos, la consecuencia es:", opciones: ["Eliminación automática de puntos", "Suspensión más prolongada", "Reducción de multa", "Advertencia sin registro"], correcta: 1 },
    { pregunta: "279. No usar dispositivos de seguridad para menores constituye:", opciones: ["Categoría A", "Categoría B", "Falta sin puntos", "Sanción penal inmediata"], correcta: 1 },
    { pregunta: "280. El uso del teléfono celular mientras se conduce se clasifica como:", opciones: ["Conducción temeraria", "Infracción categoría B", "Infracción sin puntos", "Falta leve sin sanción"], correcta: 1 },
    { pregunta: "281. Un conductor que no usa luces reglamentarias puede recibir:", opciones: ["4 puntos en su licencia", "6 puntos en su licencia", "Solo advertencia", "Arresto inmediato"], correcta: 0 },
    { pregunta: "282. La conducción temeraria puede implicar detención de hasta:", opciones: ["24 horas", "48 horas", "72 horas", "96 horas"], correcta: 3 },
    { pregunta: "283. Conducir a velocidades extremadamente altas se considera:", opciones: ["Infracción leve", "Conducción preventiva", "Conducción temeraria", "Error administrativo"], correcta: 2 },
    { pregunta: "284. Una sanción administrativa puede incluir:", opciones: ["Pena de prisión", "Multa o suspensión de licencia", "Arresto inmediato", "Cárcel automática"], correcta: 1 },
    { pregunta: "285. Una sanción penal puede implicar:", opciones: ["Trabajo comunitario opcional", "Multa leve sin registro", "Pena de prisión", "Descuento de puntos"], correcta: 2 },
    { pregunta: "286. Si un conductor considera injusta una boleta de tránsito, puede:", opciones: ["Ignorarla", "Impugnarla siguiendo el procedimiento legal", "Transferirla a otra persona", "Romperla"], correcta: 1 },
    { pregunta: "287. Ceder el paso significa:", opciones: ["Acelerar para pasar primero", "Permitir prioridad al usuario correspondiente", "Detenerse siempre, aunque no sea necesario", "Ignorar la señalización"], correcta: 1 },
    { pregunta: "288. No ceder el paso a peatones constituye:", opciones: ["Conducta permitida", "Conducta de riesgo sancionable", "Falta moral sin multa", "Solo recomendación"], correcta: 1 },
    { pregunta: "289. Permitir exceso de pasajeros en el vehículo:", opciones: ["Es práctica común sin sanción", "Es conducta de riesgo", "Solo aplica a autobuses", "Es permitido en trayectos cortos"], correcta: 1 },
    { pregunta: "290. Conducir con exceso de carga puede:", opciones: ["Mejorar estabilidad", "Generar sanción y riesgo vial", "No tener consecuencias", "Solo afectar el consumo"], correcta: 1 },
    { pregunta: "291. Alterar dispositivos de seguridad ferroviaria es:", opciones: ["Falta administrativa leve", "Conducta de alto riesgo", "Solo advertencia", "Acción sin consecuencias"], correcta: 1 },
    { pregunta: "292. Las sanciones penales pueden aplicarse cuando:", opciones: ["Se estaciona mal", "Hay conducción temeraria", "Se olvida el cinturón", "Se usa direccional incorrectamente"], correcta: 1 },
    { pregunta: "293. El sistema de puntos se aplica cuando:", opciones: ["Se cometen infracciones que así lo establecen", "Se paga marchamo tarde", "Se cambia de vehículo", "Se renueva licencia"], correcta: 0 },
    { pregunta: "294. El objetivo principal de las normas de tránsito es:", opciones: ["Recaudar dinero", "Proteger la vida y la seguridad vial", "Limitar el uso del vehículo", "Aumentar la cantidad de multas"], correcta: 1 },
    { pregunta: "295. Si una persona pierde el derecho a conducir por acumulación de puntos:", opciones: ["Puede seguir conduciendo si paga multa", "Debe cumplir el periodo de suspensión", "Solo pierde puntos sin efecto real", "Puede delegar su licencia"], correcta: 1 },
    { pregunta: "296. El incumplimiento de normas puede generar consecuencias:", opciones: ["Solo económicas", "Económicas, administrativas y penales", "Solo administrativas", "Solo penales"], correcta: 1 },
    { pregunta: "297. El compromiso individual del conductor es fundamental porque:", opciones: ["Las normas no son obligatorias", "La seguridad vial depende del comportamiento de cada persona", "Solo la policía controla la seguridad", "El sistema elimina errores automáticamente"], correcta: 1 },
    { pregunta: "298. Una infracción categoría A implica mayor gravedad que categoría B porque:", opciones: ["Acumula menos puntos", "No genera multa", "Representa conductas de alto riesgo", "Solo aplica a conductores profesionales"], correcta: 2 },
    { pregunta: "299. El arresto inmediato puede aplicarse en casos de:", opciones: ["Estacionamiento incorrecto leve", "Conducción temeraria", "No usar direccional", "Uso de luces bajas"], correcta: 1 },
    { pregunta: "300. Las normas de tránsito existen principalmente para:", opciones: ["Castigar conductores", "Regular la movilidad y proteger vidas", "Aumentar sanciones", "Favorecer a ciertos usuarios"], correcta: 1 }
];
