const bancoPreguntas = [
   { pregunta: "Según el texto, conducir no es solo encender el vehículo porque también requiere:", opciones: ["Saber mecánica avanzada", "Conocimientos de normas y factores de seguridad vial", "Solo habilidad física", "Saber cambiar marchas"], correcta: 1 },
    { pregunta: "El objetivo general del tema es:", opciones: ["Comprender movilidad y conducción segura en Costa Rica", "Aprender a manejar vehículos pesados", "Memorizar señales de tránsito", "Reducir el uso del transporte público"], correcta: 0 },
    { pregunta: "Conducir debe desarrollarse dentro de un marco de:", opciones: ["Competencia y rapidez", "Prioridad solo para automóviles", "Respeto mutuo, tolerancia y protección de la vida", "Libertad sin normas"], correcta: 2 },
    { pregunta: "¿Cuál de los siguientes NO se menciona como usuario del sistema vial?", opciones: ["Pilotos de avión", "Peatones", "Ciclistas", "Conductores de autobuses"], correcta: 0 },
    { pregunta: "Un conductor novato se considera novato durante:", opciones: ["1 año", "5 años", "3 años", "2 años"], correcta: 3 },
    { pregunta: "El conductor profesional se caracteriza por:", opciones: ["Tener licencia A1 únicamente", "Renovar licencia cada 6 meses", "No necesitar acreditación", "Conducir como actividad laboral principal"], correcta: 3 },
    { pregunta: "El “conductor común” (no tipificado) es quien:", opciones: ["Es profesional acreditado", "No tiene licencia", "Tiene más de 3 años de licencia y no es profesional", "Tiene menos de 3 años de licencia"], correcta: 2 },
    { pregunta: "Conductor no acreditado es:", opciones: ["Quien no cuenta con el tipo de licencia correspondiente", "Quien tiene licencia vigente", "Quien conduce taxi", "Quien conduce bicicleta"], correcta: 0 },
    { pregunta: "La movilidad es fundamental porque permite:", opciones: ["Solo recreación", "Solo trabajo", "Desplazamiento por trabajo, estudio, recreación y acceso a servicios", "Únicamente transporte privado"], correcta: 2 },
    { pregunta: "El enfoque de “sistema seguro” reconoce que:", opciones: ["El ser humano puede cometer errores y el sistema debe reducir consecuencias", "El conductor nunca se equivoca", "La seguridad depende solo del vehículo", "Solo se necesita más policía"], correcta: 0 },
    { pregunta: "Una acción incluida en el “sistema seguro” es:", opciones: ["Aumentar velocidad en autopistas", "Infraestructura vial segura", "Quitar ciclovías", "Reducir semáforos"], correcta: 1 },
    { pregunta: "¿Cuál es una de las cinco acciones del sistema seguro?", opciones: ["Más vehículos sin mantenimiento", "Mejor asistencia a las víctimas", "Menos controles policiales", "Menos educación vial"], correcta: 1 },
    { pregunta: "El ejemplo de movilidad sostenible menciona como mejora:", opciones: ["Más presas", "Menos señalización", "Más adelantamientos", "Carriles exclusivos para bicicletas y semáforos peatonales adecuados"], correcta: 3 },
    { pregunta: "Un factor de riesgo se define como:", opciones: ["Condición que aumenta la probabilidad de accidente y lesiones graves", "Algo que elimina accidentes", "Solo una multa", "Una señal de tránsito"], correcta: 0 },
    { pregunta: "Los factores de riesgo pueden relacionarse con:", opciones: ["Carretera, vehículo, conducta del conductor y atención post accidente", "Solo la carretera", "Solo el conductor", "Solo el clima"], correcta: 0 },
    { pregunta: "Según la OMS, “exposición al riesgo” incluye:", opciones: ["Consumo de alcohol", "No usar casco", "Distancias de traslado y falta de aceras/ciclovías", "Atención postraumática"], correcta: 2 },
    { pregunta: "“Posibilidad de que ocurra un accidente” incluye:", opciones: ["Retrasos en la detección", "Rehabilitación", "Diseño de la vía", "Mal estado de carreteras y distracción"], correcta: 3 },
    { pregunta: "“Gravedad de las lesiones” se relaciona con:", opciones: ["No usar cinturón/casco/SRI y diseño de la vía", "Falta de servicios de emergencia", "Volumen de tránsito", "Distancias de traslado"], correcta: 0 },
    { pregunta: "“Evolución de las lesiones después del accidente” incluye:", opciones: ["No usar casco", "Traslado al centro médico y atención postraumática", "Exceso de velocidad", "Tipo de vehículo"], correcta: 1 },
    { pregunta: "Un accidente de tránsito, según el texto, es:", opciones: ["Un daño sin infracción", "Un acto intencional siempre", "Una acción culposa con muerte, lesiones o daños materiales por infracción", "Un evento solo material sin ley"], correcta: 2 },
    { pregunta: "Colisión es:", opciones: ["Volcar el carro", "Golpear peatón", "Salirse a la cuneta sin daño", "Choque entre vehículos o contra objeto fijo"], correcta: 3 },
    { pregunta: "Vuelco ocurre cuando:", opciones: ["El vehículo pierde estabilidad y se voltea", "Se frena suave", "Se cambia de carril", "Se estaciona mal"], correcta: 0 },
    { pregunta: "Atropello es:", opciones: ["Choque contra pared", "Golpear a una persona o animal con un vehículo", "Choque trasero", "Cambio de carril"], correcta: 1 },
    { pregunta: "Choque de frente suele ocurrir por:", opciones: ["Invadir carril contrario por adelantamiento indebido", "Mantener distancia", "Usar cinturón", "Bajar velocidad"], correcta: 0 },
    { pregunta: "Colisión trasera se relaciona principalmente con:", opciones: ["Buen mantenimiento", "Señalización adecuada", "No guardar distancia, distracción o exceso de velocidad", "Carril exclusivo"], correcta: 2 },
    { pregunta: "Colisión lateral ocurre generalmente por:", opciones: ["Frenar en recta", "Manejar en reversa 1 km", "Usar luces bajas", "Giro o cambio de carril"], correcta: 3 },
    { pregunta: "La DAM (Declaración de Accidente Menor) aplica cuando hay:", opciones: ["Solo daños materiales sin personas heridas", "Heridos", "Choque con muerte", "Daños a peatones"], correcta: 0 },
    { pregunta: "La DAM busca:", opciones: ["Aumentar congestión", "Evitar reportes", "Resolver ágilmente y evitar presas", "Sustituir a emergencias médicas"], correcta: 2 },
    { pregunta: "En el caso de Julián, un factor de riesgo de la vía fue:", opciones: ["Baches y falta de señalización", "Neumáticos desgastados", "Cinturón puesto", "Motor nuevo"], correcta: 0 },
    { pregunta: "En el caso de Julián, un factor de riesgo del vehículo fue:", opciones: ["Lluvia", "Baches", "Ambulancia cerca", "Neumáticos muy desgastados"], correcta: 3 },
    { pregunta: "En el caso de Julián, la conducta riesgosa fue:", opciones: ["Reducir velocidad", "Ir a 80 km/h en lluvia y baja visibilidad", "Detenerse a revisar llantas", "No adelantar"], correcta: 1 },
    { pregunta: "Una acción que pudo prevenir el accidente fue:", opciones: ["Aumentar velocidad para pasar rápido", "Ignorar baches", "Quitar cinturón", "Reducir velocidad en lluvia"], correcta: 3 },
    { pregunta: "Una consecuencia del accidente en el caso fue:", opciones: ["Contusiones y daños materiales", "Sin daños", "Solo multa", "Mejoró la visibilidad"], correcta: 0 },
    { pregunta: "Después de un accidente se debe:", opciones: ["Irse sin avisar", "Solicitar ayuda, asegurar zona y reportar según corresponda", "Discutir con otros conductores", "Bloquear la vía"], correcta: 1 },
    { pregunta: "Vehículos motorizados se desplazan por:", opciones: ["Motor eléctrico/híbrido/gasolina/diésel", "Fuerza humana", "Tracción animal", "Empuje manual"], correcta: 0 },
    { pregunta: "Vehículos no motorizados incluyen:", opciones: ["Camiones", "Bicicletas y triciclos no motorizados", "Trenes", "Autobuses"], correcta: 1 },
    { pregunta: "Ciclovías son:", opciones: ["Exclusivas para carros", "Destinadas al tránsito de bicicletas y triciclos no motorizados", "Para estacionar", "Solo para motos"], correcta: 1 },
    { pregunta: "Aceras son:", opciones: ["Para vehículos", "Para camiones", "Exclusivas para peatones", "Para bicicletas"], correcta: 2 },
    { pregunta: "Espaldón es:", opciones: ["Carril rápido", "Zona exclusiva buses", "Ciclovía", "Sección contigua a la calzada para emergencias/peatones/estacionamiento según condiciones"], correcta: 3 },
    { pregunta: "Cuneta o sistema de drenaje permite:", opciones: ["Flujo de agua de lluvia en carretera", "Mayor velocidad", "Cambiar carriles", "Estacionar buses"], correcta: 0 },
    { pregunta: "Carreteras primarias:", opciones: ["Son senderos", "Soportan alto tránsito y conectan puntos importantes", "Solo en zonas rurales", "No conectan ciudades"], correcta: 1 },
    { pregunta: "Calles locales son:", opciones: ["Dentro del cuadrante de un área urbana", "Fuera del área urbana", "Caminos de herradura", "Carreteras primarias"], correcta: 0 },
    { pregunta: "Caminos vecinales sirven para:", opciones: ["Acceso a fincas, haciendas, pueblos o centros poblados", "Conectar rutas primarias", "Solo autopistas", "Solo bicicletas"], correcta: 0 },
    { pregunta: "En Costa Rica, la edad mínima general para obtener licencia es:", opciones: ["16", "21", "18", "17"], correcta: 2 },
    { pregunta: "La excepción de edad mínima mencionada es para:", opciones: ["A1 a los 16", "B-1 a los 16", "B-2 a los 16", "D a los 16"], correcta: 0 },
    { pregunta: "Un requisito para obtener licencia clase B es:", opciones: ["No saber leer ni escribir", "Tener 15 años", "Aprobar curso teórico de educación vial", "No presentar dictamen médico"], correcta: 2 },
    { pregunta: "El Permiso Temporal de Aprendizaje tiene vigencia de:", opciones: ["1 mes", "3 meses", "2 meses", "6 meses"], correcta: 1 },
    { pregunta: "Para permiso temporal, el aspirante debe conducir:", opciones: ["Acompañado por persona con licencia del mismo tipo o superior, vigente, con 5 años o más", "Solo, siempre", "Con cualquier amigo", "Solo de noche"], correcta: 0 },
    { pregunta: "Para la prueba práctica, debe presentarse:", opciones: ["5 minutos antes", "10 minutos antes", "30 minutos antes", "1 hora después"], correcta: 2 },
   const bancoPreguntasParte2 = [
    { pregunta: "La regla de los 3 segundos sirve para:", opciones: ["Saber cuándo usar bocina", "Calcular distancia segura entre vehículos", "Medir velocidad máxima", "Cambiar de carril sin señalizar"], correcta: 1 },
    { pregunta: "La señalización en la vía es fundamental principalmente para:", opciones: ["Aumentar la velocidad", "La seguridad al conducir", "Reducir el uso de ciclovías", "Evitar que haya peatones"], correcta: 1 },
    { pregunta: "Estudiar el significado de cada señal ayuda a:", opciones: ["Evitar accidentes y multas", "Manejar sin licencia", "Saltarse semáforos", "No usar cinturón"], correcta: 0 },
    { pregunta: "El objetivo general del tema es:", opciones: ["Memorizar nombres de calles", "Aprender mecánica", "Diferenciar señales según función y clasificación para conducir seguro", "Conducir solo en autopista"], correcta: 2 },
    { pregunta: "Un objetivo específico es:", opciones: ["Ignorar señales horizontales", "Identificar señales y su significado", "Conducir sin normas", "Acelerar en zonas escolares"], correcta: 1 },
    { pregunta: "Las señales de tránsito son:", opciones: ["Normas que ordenan la vía y regulan conducta", "Sugerencias sin obligación", "Solo dibujos decorativos", "Exclusivas para conductores"], correcta: 0 },
    { pregunta: "Además de obligación legal, las señales también son:", opciones: ["Un gasto", "Un permiso opcional", "Una advertencia solo para peatones", "Una responsabilidad personal"], correcta: 3 },
    { pregunta: "Las señales funcionan como un sistema de:", opciones: ["Publicidad", "Entretenimiento", "Comunicación", "Competencia"], correcta: 2 },
    { pregunta: "Las señales nos informan sobre todo, EXCEPTO:", opciones: ["Prioridades", "Marca de llantas", "Riesgos", "Condiciones de la vía"], correcta: 1 },
    { pregunta: "Las señales de reglamentación indican:", opciones: ["Lugares turísticos", "Solo servicios", "Obligaciones, prohibiciones o restricciones", "Solo obras"], correcta: 2 },
    { pregunta: "Las señales de reglamentación generalmente son:", opciones: ["Triangulares y rojas", "Rectangulares verdes", "Rombo amarillo", "Circulares, fondo blanco con borde rojo"], correcta: 3 },
    { pregunta: "Ejemplo de señal de reglamentación:", opciones: ["Hospital", "ALTO", "Curva peligrosa", "Derrumbe"], correcta: 1 },
    { pregunta: "Las señales de reglamentación son:", opciones: ["Opcionales", "De cumplimiento obligatorio", "Solo para ciclistas", "Solo de noche"], correcta: 1 },
    { pregunta: "Las señales de prevención sirven para:", opciones: ["Prohibir estacionar", "Indicar hoteles", "Advertir peligros reales o potenciales", "Marcar carriles de buses"], correcta: 2 },
    { pregunta: "Las señales de prevención generalmente son:", opciones: ["Fondo blanco circular", "Fondo amarillo y forma rombo", "Fondo verde rectangular", "Fondo azul circular"], correcta: 1 },
    { pregunta: "Ejemplo de señal de prevención:", opciones: ["No parquear", "Gasolinera", "Nombre de calle", "Zona escolar"], correcta: 3 },
    { pregunta: "Las señales de prevención alertan para:", opciones: ["Acelerar", "Adelantar sin mirar", "Reducir velocidad y estar atentos", "Ignorar el riesgo"], correcta: 2 },
    { pregunta: "Las señales de información sirven para:", opciones: ["Prohibir giros", "Orientar y guiar al conductor", "Advertir derrumbes", "Indicar multas"], correcta: 1 },
    { pregunta: "Ejemplo de señal informativa:", opciones: ["Curva peligrosa", "Prohibido girar", "Reductor de velocidad", "Hotel"], correcta: 3 },
    { pregunta: "Las señales horizontales son:", opciones: ["Solo semáforos", "Solo rótulos verticales", "Sirenas", "Marcas pintadas en el pavimento"], correcta: 3 },
    { pregunta: "La línea amarilla separa:", opciones: ["Carriles del mismo sentido", "Sentidos opuestos de circulación", "Zonas de parqueo", "Ciclovías"], correcta: 1 },
    { pregunta: "Línea amarilla continua significa:", opciones: ["Sí se puede adelantar siempre", "Solo adelantar motos", "No se puede adelantar", "Se puede adelantar de noche"], correcta: 2 },
    { pregunta: "Línea amarilla discontinua significa:", opciones: ["No se puede adelantar nunca", "Prohíbe girar", "Obliga a parar", "Sí se puede adelantar si es seguro"], correcta: 3 },
    { pregunta: "La línea blanca separa:", opciones: ["Sentidos opuestos", "Ciclovía y acera", "Carriles del mismo sentido", "Zona escolar y hospital"], correcta: 2 },
    { pregunta: "La línea de parada indica:", opciones: ["Dónde acelerar", "Dónde adelantar", "Dónde detenerse en ALTO o CEDA", "Dónde tocar bocina"], correcta: 2 },
    { pregunta: "La “cebra” (zona peatonal) sirve para:", opciones: ["Estacionar", "Adelantar buses", "Proteger el paso de peatones", "Marcar carril reversible"], correcta: 2 },
    { pregunta: "La zona de estacionamiento sirve para:", opciones: ["Delimitar espacios para parquear", "Separar sentidos opuestos", "Indicar hospital", "Prohibir buses"], correcta: 0 },
    { pregunta: "El color verde en demarcación se usa para:", opciones: ["Carriles compartidos con ciclistas", "Prohibido girar", "Ceda el paso", "Zona de buses"], correcta: 0 },
    { pregunta: "El color azul en demarcación indica:", opciones: ["Zonas de carga", "Carril reversible", "Espacios para personas con discapacidad", "Línea de parada"], correcta: 2 },
    { pregunta: "La canalización se usa para:", opciones: ["Indicar hoteles", "Guiar el flujo vehicular en intersecciones complejas", "Prohibir semáforos", "Marcar ciclovía solo con blanco"], correcta: 1 },
    { pregunta: "El carril central de giro izquierdo:", opciones: ["Se usa para adelantar", "Es exclusivo de buses", "Se usa como parqueo", "Permite girar a la izquierda con seguridad"], correcta: 3 },
    { pregunta: "El carril exclusivo para buses es:", opciones: ["Para todos los vehículos", "Solo para transporte público", "Para bicicletas", "Para motos únicamente"], correcta: 1 },
    { pregunta: "El carril reversible se usa para:", opciones: ["Aumentar multas", "Evitar semáforos", "Descongestionar zonas conflictivas", "Sustituir ciclovías"], correcta: 2 },
    { pregunta: "El carril reversible funciona:", opciones: ["Siempre igual", "Solo en zonas rurales", "Solo de noche", "Por horarios"], correcta: 3 },
    { pregunta: "La caja amarilla (cajón) indica:", opciones: ["Adelantar en intersección", "Zona de estacionamiento", "Prohibido bloquear intersecciones", "Zona escolar"], correcta: 2 },
    { pregunta: "¿Qué se debe evitar con la caja amarilla?", opciones: ["Girar a la izquierda", "Usar direccional", "Bajar velocidad", "Quedarse detenido dentro si no se puede salir"], correcta: 3 },
    { pregunta: "La ciclovía es:", opciones: ["Carril exclusivo para bicicletas", "Carril exclusivo buses", "Zona de carga", "Vía peatonal"], correcta: 0 },
    { pregunta: "Según el texto, la ciclovía se marca en color:", opciones: ["Amarillo", "Azul", "Blanco", "Naranja"], correcta: 2 },
    { pregunta: "Los reductores de velocidad se colocan para:", opciones: ["Obligar a aumentar velocidad", "Indicar destinos", "Obligar a disminuir velocidad", "Marcar parqueos"], correcta: 2 },
    { pregunta: "Un tipo de reductor de velocidad es:", opciones: ["Semáforo peatonal", "Línea blanca", "Señal informativa", "Lomo de burro"], correcta: 3 },
    { pregunta: "El paso peatonal elevado busca:", opciones: ["Proteger zonas sensibles", "Quitar señalización", "Aumentar el tráfico", "Mejorar adelantamientos"], correcta: 0 },
    { pregunta: "En semáforo vehicular, rojo significa:", opciones: ["Avanzar", "Acelerar", "Detenerse", "Rebasar"], correcta: 2 },
    { pregunta: "En semáforo vehicular, amarillo indica:", opciones: ["Precaución / detenerse", "Avanzar siempre", "No pase", "Carril reversible"], correcta: 0 },
    { pregunta: "En semáforo vehicular, verde significa:", opciones: ["Detenerse", "Avanzar", "Precaución", "No pase"], correcta: 1 },
    { pregunta: "En semáforo peatonal, rojo significa:", opciones: ["Puede cruzar", "Adelante rápido", "No pase", "Cruce por la ciclovía"], correcta: 2 },
    { pregunta: "En semáforo peatonal, verde significa:", opciones: ["No pase", "Solo bicicletas", "Puede cruzar", "Solo buses"], correcta: 2 },
    { pregunta: "Una señal luminosa transitoria indica:", opciones: ["Nombre de calles", "Prohibido parquear", "Trabajos, emergencias o desvíos", "Curva peligrosa fija"], correcta: 2 },
    { pregunta: "El señalamiento sonoro incluye:", opciones: ["Líneas amarillas", "Cajas amarillas", "Ciclovías", "Sirenas de emergencia"], correcta: 3 },
    { pregunta: "El señalamiento manual lo realizan:", opciones: ["Conductores particulares", "Oficiales de tránsito", "Peatones", "Pasajeros"], correcta: 1 },
    { pregunta: "En autopista, la velocidad mínima indicada en el texto es:", opciones: ["25 km/h", "50 km/h", "60 km/h", "80 km/h"], correcta: 2 },
    { pregunta: "En zona escolar u hospital, el máximo indicado es:", opciones: ["25 km/h", "40 km/h", "50 km/h", "60 km/h"], correcta: 0 },
    { pregunta: "Conducir de forma segura implica, entre otros, principalmente:", opciones: ["Manejar solo de día", "Usar únicamente transmisión automática", "Conocer el funcionamiento del vehículo y darle mantenimiento preventivo", "Conducir siempre rápido"], correcta: 2 },
    { pregunta: "Un conductor que conoce su vehículo:", opciones: ["Reduce el riesgo de accidentes", "No necesita señales", "Nunca se equivoca", "Puede ignorar el mantenimiento"], correcta: 0 },
    { pregunta: "El objetivo general del tema es:", opciones: ["Aprender a cambiar llantas sin herramientas", "Memorizar marcas de carros", "Reconocer mandos y controles del vehículo para minimizar accidentes", "Conducir en autopista únicamente"], correcta: 2 },
    { pregunta: "Los mandos y controles del automóvil incluyen:", opciones: ["Solo frenos y llantas", "Solo aire acondicionado", "Indicadores del panel, visibilidad, llantas, frenos, transmisiones y mantenimiento", "Solo radio y pantalla"], correcta: 2 },
    { pregunta: "En las luces del panel, el color rojo significa:", opciones: ["Información activa", "Revisar pronto", "Señal de mantenimiento normal", "Atención inmediata (peligro)"], correcta: 3 },
    { pregunta: "En el panel, el color amarillo/ámbar indica:", opciones: ["Detenerse siempre", "Direccionales activas", "Revisar pronto", "Que todo está normal"], correcta: 2 },
    { pregunta: "En el panel, el color verde suele indicar:", opciones: ["Peligro", "Información activa (ej. direccionales)", "Falla grave", "Sobrecalentamiento"], correcta: 1 },
    { pregunta: "El tacómetro indica:", opciones: ["Kilómetros recorridos", "Revoluciones del motor (RPM)", "Nivel de combustible", "Temperatura externa"], correcta: 1 },
    { pregunta: "El tacómetro ayuda a:", opciones: ["Evitar forzar el motor", "Saber la presión de llantas", "Medir el aceite", "Encender direccionales"], correcta: 0 },
    { pregunta: "Cuando el combustible baja mucho, suele:", opciones: ["Apagarse el motor de inmediato", "Encenderse la luz verde", "Encenderse una luz de advertencia", "Sonar la bocina"], correcta: 2 },
    { pregunta: "Si el motor está sobrecalentado, el texto indica:", opciones: ["Acelerar para enfriar", "Detenerse inmediatamente", "Abrir el radiador en caliente", "Continuar si no hay humo"], correcta: 1 },
    { pregunta: "¿Qué NO se debe hacer nunca con el radiador?", opciones: ["Revisarlo en frío", "Abrirlo en caliente", "Mantenerlo cerrado", "Revisar temperatura"], correcta: 1 },
    { pregunta: "Si la luz de batería/alternador permanece encendida:", opciones: ["Indica direccionales", "Indica nivel de aceite alto", "Puede haber falla en la carga de batería", "Indica ABS activo"], correcta: 2 },
    { pregunta: "El velocímetro muestra:", opciones: ["RPM del motor", "Kilómetros totales de vida del carro", "Velocidad en km/h", "Presión de llantas"], correcta: 2 },
    { pregunta: "El velocímetro sirve para:", opciones: ["Respetar límites legales", "Medir desgaste de llanta", "Encender luces", "Abrir el radiador"], correcta: 0 },
    { pregunta: "El odómetro indica:", opciones: ["Nivel de gasolina", "Kilómetros recorridos", "Temperatura del motor", "Potencia del motor"], correcta: 1 },
    { pregunta: "El odómetro es útil para:", opciones: ["Mantenimiento y control", "Cambiar a reversa", "Regular direccionales", "Evitar puntos ciegos"], correcta: 0 },
    { pregunta: "El indicador de freno de mano activado significa:", opciones: ["Que el ABS falló", "Que las puertas están abiertas", "Que el freno está puesto", "Que falta aceite"], correcta: 2 },
    { pregunta: "La luz de puertas abiertas indica que:", opciones: ["Falta combustible", "Alguna puerta, capó o maletero está abierto", "Hay fallo en airbag", "El motor está frío"], correcta: 1 },
    { pregunta: "El indicador del cinturón de seguridad significa que:", opciones: ["Todos lo llevan puesto", "Falló el ABS", "Hay combustible en reserva", "Un ocupante no lo lleva puesto"], correcta: 3 },
    { pregunta: "La luz de airbag encendida indica:", opciones: ["Direccionales activas", "Que está en modo deportivo", "Luces altas activas", "Falla en el sistema de bolsas de aire"], correcta: 3 },
    { pregunta: "¿Cuál es una luz del vehículo mencionada en el texto?", opciones: ["Luz de posición", "Luz de neón interior obligatoria", "Luz violeta de emergencia", "Luz de “turbo”"], correcta: 0 },
    { pregunta: "En transmisión automática, “P” significa:", opciones: ["Pista", "Parqueo", "Potencia", "Pase"], correcta: 1 },
    { pregunta: "En transmisión automática, “R” significa:", opciones: ["Rodaje", "Reversa", "Rendimiento", "Ruta"], correcta: 1 },
    { pregunta: "En transmisión automática, “D” significa:", opciones: ["Detener", "Avance", "Descanso", "Derrape"], correcta: 1 },
    { pregunta: " “L/L1” en automática se usa para:", opciones: ["Mayor fuerza (subidas)", "Retroceso rápido", "Apagar motor", "Activar ABS"], correcta: 0 },
    { pregunta: " “S” en automática indica:", opciones: ["Seguro", "Deportivo", "Suspensión", "Señal"], correcta: 1 },
    { pregunta: "Según el texto, NO se debe cambiar a P o R:", opciones: ["Con el vehículo detenido", "Con el freno de mano", "En subidas", "Con el vehículo en movimiento"], correcta: 3 },
    { pregunta: "La señal de “aceite bajo” puede:", opciones: ["Mejorar el motor", "Causar daños graves al motor", "Encender direccionales", "Aumentar presión de llantas"], correcta: 1 },
    { pregunta: "La temperatura alta del motor indica:", opciones: ["Enfriamiento normal", "Sobrecalentamiento; detenerse", "Batería baja", "ABS activo"], correcta: 1 },
    { pregunta: "El nivel bajo de combustible indica que:", opciones: ["Está lleno", "No hay marchamo", "Está en reserva", "Falló el alternador"], correcta: 2 },
    { pregunta: "“Check Engine” intermitente puede indicar:", opciones: ["Falla leve", "Falla grave siempre", "Aire en llantas", "Puerta abierta"], correcta: 0 },
    { pregunta: "“Check Engine” permanente puede indicar:", opciones: ["Información activa", "Falla grave", "Direccional activada", "Estacionamiento correcto"], correcta: 1 },
    { pregunta: "Si la luz del ABS queda encendida:", opciones: ["El sistema antibloqueo puede no funcionar correctamente", "El ABS funciona perfecto", "Indica luz baja activa", "Indica gasolina llena"], correcta: 0 },
    { pregunta: "El limpia parabrisas permite:", opciones: ["Aumentar velocidad", "Medir RPM", "Enfriar motor", "Limpiar lluvia, polvo y suciedad"], correcta: 3 },
    { pregunta: "Los vidrios y ventanas deben:", opciones: ["Tener obstrucciones para el sol", "Usarse solo de noche", "No tener obstrucciones", "Abrirse siempre"], correcta: 2 },
    { pregunta: "El espejo central:", opciones: ["Solo sirve para ver el costado", "Elimina todos los puntos ciegos", "Se ajusta con el vehículo en movimiento", "Permite ver detrás y es ajustable"], correcta: 3 },
    { pregunta: "Los espejos laterales:", opciones: ["Reducen puntos ciegos y amplían campo visual", "Solo son decorativos", "Reemplazan el parabrisas", "Se ajustan por los pasajeros"], correcta: 0 },
    { pregunta: "El espejo “ojo de pescado” sirve para:", opciones: ["Aumentar el ruido", "Medir velocidad", "Ampliar visión lateral y reducir punto ciego", "Enfriar frenos"], correcta: 2 },
    { pregunta: "La cámara de retroceso:", opciones: ["Se activa en reversa", "Se activa solo en D", "Se usa para luces altas", "Solo funciona en autopista"], correcta: 0 },
    { pregunta: "Los espejos y cámaras deben ajustarse:", opciones: ["Durante la conducción", "Antes de iniciar el viaje", "Por los pasajeros", "En movimiento y sin detenerse"], correcta: 1 },
    { pregunta: "Los espejos deben ajustarse solo cuando:", opciones: ["Va a 60 km/h", "Hay neblina", "El carro está detenido", "Hay lluvia"], correcta: 2 },
    { pregunta: "Los puntos ciegos son:", opciones: ["Zonas que se ven perfectamente con espejos", "Zonas exclusivas de ciclovías", "Zonas que solo existen de noche", "Zonas que el conductor no ve desde su asiento ni con espejos"], correcta: 3 },
    { pregunta: "Los puntos ciegos son peligrosos porque:", opciones: ["Mejoran visibilidad", "Ocultan peatones, ciclistas, motociclistas o vehículos", "Reducen accidentes", "Aumentan estabilidad del carro"], correcta: 1 },
    { pregunta: "Un método para reducir puntos ciegos es:", opciones: ["No usar espejos", "Acelerar para salir rápido", "Girar la cabeza y observar antes de maniobrar", "Manejar solo por el carril izquierdo"], correcta: 2 },
    { pregunta: "Según el texto, las tecnologías ADAS:", opciones: ["Eliminan por completo los puntos ciegos", "Sustituyen al conductor", "Alertan con sensores sobre vehículos en puntos ciegos", "Son solo decorativas"], correcta: 2 },
    { pregunta: "Aunque existan ayudas, los puntos ciegos:", opciones: ["Se eliminan totalmente", "Solo existen en motos", "Solo existen en reversa", "No se eliminan por completo; hay que conducir con precaución"], correcta: 3 },
    { pregunta: "Las luces del vehículo deben servir para:", opciones: ["Ver, ser visto y alertar", "Solo decorar", "Solo iluminar la placa", "Solo encender en autopista"], correcta: 0 },
    { pregunta: "La luz alta (larga) ilumina aproximadamente:", opciones: ["30 metros", "100 metros", "10 metros", "200 metros"], correcta: 1 },
    { pregunta: "Las luces bajas son obligatorias, según el texto:", opciones: ["De 6:00 a.m. a 6:00 p.m.", "De 6:00 p.m. a 6:00 a.m.", "Solo en lluvia", "Solo en autopista"], correcta: 1 },
   { pregunta: "El objetivo general del tema de maniobras es:", opciones: ["Manejar solo en ciudad", "Fomentar habilidades para maniobras seguras en carretera", "Aprender mecánica básica", "Evitar usar direccionales"], correcta: 1 },
    { pregunta: "Un objetivo específico del tema es:", opciones: ["Manejar sin retrovisores", "Aumentar velocidad en curvas", "Reconocer procedimientos correctos para adelantamientos y frenados", "Estacionar solo en puentes"], correcta: 2 },
    { pregunta: "Al conducir, siempre realizamos maniobras para:", opciones: ["Solo acelerar", "Avanzar, detenernos, girar y esquivar obstáculos", "Solo frenar", "Solo estacionar"], correcta: 1 },
    { pregunta: "Un momento clave para maniobras es:", opciones: ["Antes de conducir, durante y finalización del viaje", "Solo durante la conducción", "Solo al final del viaje", "Solo al arrancar"], correcta: 0 },
    { pregunta: "La postura correcta del conductor incluye:", opciones: ["Espalda encorvada para ver mejor", "Rodillas totalmente estiradas", "Pedales lejos para mayor fuerza", "Espalda recta y postura cómoda"], correcta: 3 },
    { pregunta: "Las rodillas deben estar:", opciones: ["Totalmente estiradas", "Pegadas al volante", "Ligeramente flexionadas", "Cruzadas"], correcta: 2 },
    { pregunta: "La distancia mínima recomendada entre pecho y volante es:", opciones: ["5 cm", "10 cm", "20 cm", "40 cm"], correcta: 2 },
    { pregunta: "La inclinación del asiento debe ser:", opciones: ["Totalmente hacia atrás", "Ligeramente reclinado", "Totalmente vertical sin ajuste", "Inclinado hacia adelante"], correcta: 1 },
    { pregunta: "Un asiento demasiado reclinado es negativo porque:", opciones: ["Mejora el control", "Se pierde control del vehículo", "Aumenta visibilidad", "Es más aerodinámico"], correcta: 1 },
    { pregunta: "El apoyacabezas debe ubicarse:", opciones: ["A la altura del cuello", "Bajo la nuca", "A la altura de las orejas", "En la espalda"], correcta: 2 },
    { pregunta: "La función del apoyacabezas es:", opciones: ["Prevenir lesiones cervicales en choques", "Mejorar velocidad", "Activar airbag", "Reducir consumo"], correcta: 0 },
    { pregunta: "El cinturón de seguridad debe colocarse:", opciones: ["Después de salir a carretera", "Solo si hay policía", "Antes de iniciar la marcha", "Solo en autopista"], correcta: 2 },
    { pregunta: "La banda horizontal del cinturón va sobre:", opciones: ["Abdomen", "Pelvis", "Pecho", "Cuello"], correcta: 1 },
    { pregunta: "La banda diagonal del cinturón va sobre:", opciones: ["Abdomen", "Cadera únicamente", "Cuello", "Clavícula y pecho"], correcta: 3 },
    { pregunta: "El cinturón NUNCA debe colocarse:", opciones: ["Debajo del brazo", "Sobre la clavícula", "Sobre la pelvis", "Sobre el pecho"], correcta: 0 },
    { pregunta: "En embarazadas, la banda baja del cinturón debe ir:", opciones: ["Sobre el abdomen", "Baja sobre la pelvis, no sobre el abdomen", "En el cuello", "Suelta para comodidad"], correcta: 1 },
    { pregunta: "En niños, el texto indica usar:", opciones: ["Cinturón debajo del brazo", "Silla adecuada según edad y peso", "Solo el asiento delantero", "Nada si es trayecto corto"], correcta: 1 },
    { pregunta: "Según el texto, el cinturón es:", opciones: ["Un hábito secundario", "Útil solo en choques leves", "El principal hábito de seguridad", "Solo para el conductor"], correcta: 2 },
    { pregunta: "Los retrovisores deben ajustarse:", opciones: ["Mientras se conduce", "Antes de arrancar", "Solo por el pasajero", "Solo si hay lluvia"], correcta: 1 },
    { pregunta: "Ajustar retrovisores ayuda a:", opciones: ["Eliminar puntos ciegos y anticipar riesgos", "Aumentar consumo de gasolina", "Hacer adelantamientos sin revisar", "Manejar sin direccionales"], correcta: 0 },
    { pregunta: "Antes de salir, es importante conocer:", opciones: ["Ubicación de pedales, palanca, luces, direccionales y emergencia", "Solo la radio", "Solo el aire acondicionado", "Solo el GPS"], correcta: 0 },
    { pregunta: "Si es un vehículo que no conoce, debe:", opciones: ["Salir de una vez", "Acelerar más para adaptarse", "Ajustar espejos en movimiento", "Verificar todo antes de salir"], correcta: 3 },
    { pregunta: "Antes de arrancar se debe revisar:", opciones: ["Solo el lado izquierdo", "Adelante, atrás y lados", "Solo atrás", "Solo el tablero"], correcta: 1 },
    { pregunta: "La revisión del entorno busca confirmar que no haya cerca:", opciones: ["Solo autos", "Niños, peatones o animales", "Solo señales", "Semáforos"], correcta: 1 },
    { pregunta: "La sujeción del volante recomendada es:", opciones: ["“2 y 2”", "“10 y 10”", "“6 y 6”", "Con una mano siempre"], correcta: 1 },
    { pregunta: "La posición “10 y 10” permite:", opciones: ["Menor control", "Mejor control y reacción rápida", "Solo comodidad", "Frenar más lento"], correcta: 1 },
    { pregunta: "Al iniciar la marcha se recomienda:", opciones: ["Salir acelerando fuerte", "Iniciar suave y progresivamente, a baja velocidad", "Iniciar en velocidad alta", "Salir sin revisar entorno"], correcta: 1 },
    { pregunta: "En salida en pendiente hacia arriba se recomienda:", opciones: ["No usar freno de mano", "Solo reversa", "Freno de mano activado y soltar progresivamente", "Acelerar al máximo"], correcta: 2 },
    { pregunta: "En salida en pendiente hacia abajo se recomienda:", opciones: ["Primera marcha y control del freno", "Neutro para bajar fácil", "Acelerar fuerte", "Apagar el motor"], correcta: 0 },
    { pregunta: "Ingresar al flujo vehicular es riesgoso porque:", opciones: ["No se usan espejos", "Siempre hay semáforo", "Es una de las maniobras más riesgosas del manejo", "Solo pasan buses"], correcta: 2 },
    { pregunta: "Para ingresar al flujo vehicular, se debe:", opciones: ["Ingresar sin obligar a otros a frenar bruscamente", "Entrar obligando a otros a frenar", "No revisar ciclistas", "No calcular velocidades"], correcta: 0 },
    { pregunta: "Antes de adelantar, se debe verificar:", opciones: ["Que haya línea continua", "Que haya rotonda", "Zona permitida y buena visibilidad", "Que sea puente"], correcta: 2 },
    { pregunta: "Antes de adelantar, NO debe hacerse en:", opciones: ["Rectas con visibilidad", "Zonas permitidas", "Carretera despejada", "Puentes, intersecciones o pasos peatonales"], correcta: 3 },
    { pregunta: "Antes de adelantar se debe revisar:", opciones: ["Retrovisores y ángulo muerto", "Solo el velocímetro", "Solo el asiento", "Solo el tablero"], correcta: 0 },
    { pregunta: "Antes de adelantar, se debe activar:", opciones: ["Direccional derecha", "Luces de emergencia", "Direccional izquierda", "Luz alta fija"], correcta: 2 },
    { pregunta: "Durante el adelantamiento se recomienda:", opciones: ["Manejo lento y largo", "Apagar direccional", "Maniobra rápida y segura, con ambas manos al volante", "Invadir carril contrario el mayor tiempo posible"], correcta: 2 },
    { pregunta: "Después de adelantar, se debe:", opciones: ["Quedarse en carril izquierdo siempre", "Frenar fuerte de inmediato", "Apagar luces", "Señalizar regreso al carril derecho"], correcta: 3 },
    { pregunta: "Después de adelantar, se debe mantener:", opciones: ["Distancia segura con el vehículo adelantado", "Cero distancia para avanzar", "Distancia solo si llueve", "Distancia solo con buses"], correcta: 0 },
    { pregunta: "Para adelantar motocicletas o bicicletas, se debe mantener mínimo:", opciones: ["0.50 m", "1.50 m", "1.00 m", "2.50 m"], correcta: 1 },
    { pregunta: "Está prohibido adelantar cuando hay:", opciones: ["Línea discontinua siempre", "Línea amarilla o blanca continua", "Zona amplia y recta", "Buena visibilidad"], correcta: 1 },
    { pregunta: "Está prohibido adelantar dentro de:", opciones: ["Rectas", "Autopista", "Rotonda", "Calle local"], correcta: 2 },
    { pregunta: "Está prohibido adelantar con:", opciones: ["Neblina o lluvia intensa", "Buena visibilidad", "Carretera seca", "Poca circulación"], correcta: 0 },
    { pregunta: "Si el vehículo delantero ya va al límite de velocidad:", opciones: ["Debe adelantar igual", "Se acelera sin mirar", "No se debe adelantar", "Se adelanta en curva"], correcta: 2 },
    { pregunta: "Si un vehículo en sentido contrario invade su carril adelantando, usted debe:", opciones: ["Mantener velocidad y esperar", "Acelerar para ganar", "Disminuir velocidad y advertir con luces", "Cambiarse al carril contrario"], correcta: 2 },
    { pregunta: "Si es necesario para evitar choque con un vehículo invasor, se recomienda:", opciones: ["Nunca frenar", "Tocar bocina y seguir", "Acelerar siempre", "Orillarse o detenerse completamente si hace falta"], correcta: 3 },
    { pregunta: "Maniobras que NO son adelantamiento (por obstáculos) requieren:", opciones: ["Verificar carril contrario libre y usar direccional", "No usar direccional", "Adelantar sin revisar", "Pasar rápido sin mirar"], correcta: 0 },
    { pregunta: "Si no puede esquivar el obstáculo de forma segura, debe:", opciones: ["Acelerar fuerte", "Invadir carril contrario igual", "Detenerse y encender luces de emergencia", "Apagar luces"], correcta: 2 },
    { pregunta: "La reversa se usa:", opciones: ["Siempre en autopista", "Para adelantar", "En curvas", "Solo en casos necesarios (estacionar o fuerza mayor)"], correcta: 3 },
    { pregunta: "En reversa, la velocidad debe ser:", opciones: ["Alta para terminar rápido", "Muy baja (máx. 20 km/h)", "60 km/h", "30 km/h"], correcta: 1 },
    { pregunta: "Nunca se debe usar reversa en:", opciones: ["Autopistas, curvas, túneles o puentes", "Estacionamientos", "Calles residenciales", "Lugares permitidos"], correcta: 0 },
    { pregunta: "La seguridad vial es fundamental principalmente para:", opciones: ["Aumentar el flujo vehicular", "Reducir la cantidad de vehículos", "Proteger la vida de conductores, pasajeros y peatones", "Evitar el uso de cinturón"], correcta: 2 },
    { pregunta: "Según el texto, a mayor cantidad de vehículos:", opciones: ["Menor riesgo", "Mayor riesgo", "No cambia el riesgo", "Solo cambia en autopistas"], correcta: 1 },
    { pregunta: "Un accidente puede deberse a:", opciones: ["Condiciones climáticas adversas", "Distracciones", "Mal estado del vehículo", "Todas las anteriores"], correcta: 3 },
    { pregunta: "La clave para reducir accidentes es:", opciones: ["Acelerar más", "Identificar riesgos y aplicar medidas preventivas", "Conducir solo de día", "Evitar puentes siempre"], correcta: 1 },
    { pregunta: "La conducción segura depende de:", opciones: ["Atención constante, velocidad adecuada, control emocional y vehículo en buen estado", "Solo velocidad alta", "Solo experiencia", "Solo frenos nuevos"], correcta: 0 },
    { pregunta: "Una zona de mayor riesgo mencionada es:", opciones: ["Parqueos bajo techo", "Calles con semáforos nuevos", "Curvas cerradas", "Zonas con aceras amplias"], correcta: 2 },
    { pregunta: "La seguridad pasiva del vehículo se refiere a:", opciones: ["Sistemas de entretenimiento", "Luces de lujo", "Aumento de potencia", "Dispositivos que protegen en caso de accidente"], correcta: 3 },
    { pregunta: "Un ejemplo de seguridad pasiva es:", opciones: ["Radio", "GPS", "Cinturón de seguridad", "Aire acondicionado"], correcta: 2 },
    { pregunta: "La seguridad pasiva busca principalmente:", opciones: ["Reducir la gravedad de lesiones", "Aumentar velocidad", "Evitar multas", "Mejorar consumo de combustible"], correcta: 0 },
    { pregunta: "El cinturón debe ajustarse de manera que la banda superior vaya:", opciones: ["En el cuello", "Bajo el brazo", "Sobre el abdomen", "Sobre el hombro"], correcta: 3 },
    { pregunta: "La banda inferior del cinturón debe ir:", opciones: ["Sobre el abdomen", "En el cuello", "Sobre la cadera", "En el brazo"], correcta: 2 },
    { pregunta: "Es incorrecto con el cinturón:", opciones: ["Ajustarlo correctamente", "Colocarlo sobre el hombro", "Pasarlo bajo el brazo", "Colocarlo sobre la cadera"], correcta: 2 },
    { pregunta: "Según el texto, NUNCA se debe:", opciones: ["Llevar niños en las rodillas", "Usar cinturón", "Ajustar el cinturón", "Usar SRI"], correcta: 0 },
    { pregunta: "El cinturón reduce el riesgo de:", opciones: ["Solo multas", "Solo cansancio", "Lesiones graves y muerte", "Solo derrapes"], correcta: 2 },
    { pregunta: "El airbag:", opciones: ["Reemplaza el cinturón", "Se activa en lluvia", "Complementa al cinturón", "Se activa al frenar suave"], correcta: 2 },
    { pregunta: "El airbag se activa principalmente en:", opciones: ["Impacto frontal", "Viento fuerte", "Frenado normal", "Giro a la izquierda"], correcta: 0 },
    { pregunta: "Niños menores de 13 años no deben viajar adelante con:", opciones: ["Ventanas cerradas", "Cinturón bien puesto", "Música baja", "Airbag activado"], correcta: 3 },
    { pregunta: "El lugar más seguro para menores de 13 años es:", opciones: ["Asiento delantero", "En las rodillas", "Asiento trasero", "En el asiento del conductor"], correcta: 2 },
    { pregunta: "El sistema de retención infantil debe elegirse según:", opciones: ["Peso y estatura (no solo edad)", "Color de la silla", "Marca del carro", "Distancia del viaje"], correcta: 0 },
    { pregunta: "Los SRI deben estar:", opciones: ["Sueltos para comodidad", "Solo en viajes largos", "Homologados y bien instalados", "Solo si hay policía"], correcta: 2 },
    { pregunta: "El chasis y carrocería están diseñados para:", opciones: ["Aumentar el ruido", "Aumentar la velocidad", "Absorber energía del impacto", "Reducir gasolina"], correcta: 2 },
    { pregunta: "Los cristales de seguridad se fragmentan en:", opciones: ["Pedazos grandes", "Láminas filosas", "Pequeños trozos para evitar cortaduras graves", "Polvo"], correcta: 2 },
    { pregunta: "Ante condiciones inesperadas, el texto recomienda:", opciones: ["Máxima atención y ajustar velocidad según clima y entorno", "Distracción controlada", "Acelerar para pasar rápido", "Conducir sin luces"], correcta: 0 },
    { pregunta: "En lluvia, un riesgo mencionado es:", opciones: ["Mayor adherencia", "Mejor visibilidad", "Menor adherencia", "Menos aceite en la vía"], correcta: 2 },
    { pregunta: "En lluvia, una consecuencia puede ser:", opciones: ["Mayor control", "Derrapes", "Más adherencia", "Mayor estabilidad siempre"], correcta: 1 },
    { pregunta: "En lluvia, se recomienda:", opciones: ["Aumentar velocidad", "No usar luces", "Frenar bruscamente", "Reducir velocidad y aumentar distancia"], correcta: 3 },
    { pregunta: "En niebla, la recomendación es:", opciones: ["Usar luces altas", "Apagar luces", "Usar luces bajas", "Acelerar"], correcta: 2 },
    { pregunta: "En viento fuerte, se recomienda:", opciones: ["Soltar el volante para estabilizar", "Sujetar firme el volante y disminuir velocidad", "Frenar brusco siempre", "Girar con rapidez"], correcta: 1 },
    { pregunta: "En sol intenso, un riesgo es:", opciones: ["Mejor atención", "Más adherencia", "Menor fatiga", "Encandilamiento y somnolencia"], correcta: 3 },
    { pregunta: "En sol intenso, se recomienda:", opciones: ["No usar lentes", "Acelerar más", "Usar lentes con protección UV", "Conducir sin pausas"], correcta: 2 },
    { pregunta: "El hidroplaneamiento es:", opciones: ["Frenar sobre seco", "Exceso de aire en llantas", "Pérdida de contacto llanta–pavimento", "Salida en pendiente"], correcta: 2 },
    { pregunta: "Para evitar riesgos en hidroplaneamiento, se recomienda:", opciones: ["Frenar bruscamente", "Sujetar firme el volante y disminuir velocidad", "Cambiar a reversa", "Acelerar para salir"], correcta: 1 },
    { pregunta: "Sobre la carga del vehículo, se recomienda:", opciones: ["Llevar objetos sueltos en asientos", "Poner objetos en el tablero", "Guardar todo en el maletero", "Llevar cajas en el regazo"], correcta: 2 },
    { pregunta: "En un impacto, los objetos sueltos pueden:", opciones: ["Hacerse más livianos", "Convertirse en proyectiles", "Pegarse al piso", "Desaparecer"], correcta: 1 },
    { pregunta: "El uso del celular al conducir puede causar:", opciones: ["Menor tiempo de reacción", "Mejor visualización", "Mayor tiempo de reacción y posible invasión de carril", "Mayor concentración"], correcta: 2 },
    { pregunta: "Una recomendación sobre el celular es:", opciones: ["Usarlo en semáforo verde", "Usarlo solo detenido", "Usarlo con una mano", "Usarlo en curvas"], correcta: 1 },
    { pregunta: "Manipular música al conducir puede provocar:", opciones: ["Apartar la vista y distraer manos del volante", "Mayor atención", "Mejor control", "Menos riesgo"], correcta: 0 },
    { pregunta: "Sobre música, se recomienda:", opciones: ["Cambiar canciones en curvas", "Subir volumen al máximo", "Elegirla antes de iniciar y volumen moderado", "Manipular pantalla mientras maneja"], correcta: 2 },
    { pregunta: "Con pasajeros (amigos/compañeros), se debe:", opciones: ["Permitir distracciones", "Quitar cinturón", "Aumentar velocidad", "Evitar conductas que distraigan al conductor"], correcta: 3 },
    { pregunta: "Discutir durante el viaje puede:", opciones: ["Aumentar concentración", "Mejor reflejos", "Hacer que el conductor pierda concentración", "Evitar accidentes"], correcta: 2 },
    { pregunta: "En viajes con menores, se recomienda:", opciones: ["Atenderlos mientras conduce", "Llevarlos en rodillas", "No usar SRI", "No atender necesidades del menor mientras conduce"], correcta: 3 },
    { pregunta: "Con mascotas, se recomienda:", opciones: ["Llevarlas sueltas", "Llevarlas en el regazo del conductor", "Transportarlas en dispositivos especiales", "Que se muevan libremente"], correcta: 2 },
    { pregunta: "La fatiga reduce:", opciones: ["El consumo de combustible", "La atención y coordinación", "La necesidad de descanso", "La distancia de frenado"], correcta: 1 },
    { pregunta: "Una recomendación ante somnolencia es:", opciones: ["Seguir manejando para llegar rápido", "Detenerse si siente sueño", "Tomar más riesgos", "No hacer pausas"], correcta: 1 },
    { pregunta: "El estrés y la ira pueden generar:", opciones: ["Conducción más calmada", "Reacciones agresivas e impulsividad", "Mejor control del volante", "Mayor paciencia siempre"], correcta: 1 },
    { pregunta: "Para manejar estrés/ira se recomienda:", opciones: ["Reaccionar ante provocaciones", "Aumentar velocidad", "Mantener calma y controlar emociones", "Competir con otros"], correcta: 2 },
    { pregunta: "Alcohol y drogas afectan:", opciones: ["Solo la vista", "Solo el oído", "Solo el GPS", "Reflejos, coordinación y percepción del riesgo"], correcta: 3 },
    { pregunta: "El consumo de alcohol/drogas puede provocar:", opciones: ["Multas, suspensión de licencia y hasta cárcel", "Solo advertencias", "Ninguna consecuencia", "Solo cursos"], correcta: 0 },
    { pregunta: "Algunos medicamentos pueden causar:", opciones: ["Mejor concentración", "Somnolencia, mareos, confusión y problemas de visión", "Más reflejos", "Menos riesgo"], correcta: 1 },
    { pregunta: "Si un medicamento produce efectos secundarios, el texto indica:", opciones: ["Conducir más despacio y ya", "Conducir igual", "No conducir", "Conducir solo de noche"], correcta: 2 },
    { pregunta: "¿Cuál es el propósito principal de las normas de tránsito?", opciones: ["Recaudar dinero mediante multas", "Proteger la vida y regular la movilidad", "Limitar el uso de vehículos", "Favorecer a conductores profesionales"], correcta: 1 },
    { pregunta: "La Ley de Tránsito por Vías Públicas Terrestres y Seguridad Vial regula principalmente:", opciones: ["La compra y venta de vehículos", "El precio del combustible", "La circulación de vehículos y conductas en la vía pública", "El mantenimiento mecánico"], correcta: 2 },
    { pregunta: "¿Cuál de las siguientes conductas corresponde a una infracción categoría A?", opciones: ["No usar luces reglamentarias", "Conducir bajo influencia del alcohol", "Uso del teléfono celular al conducir", "No usar direccional"], correcta: 1 },
    { pregunta: "Una infracción categoría A acumula:", opciones: ["2 puntos", "4 puntos", "6 puntos", "No acumula puntos"], correcta: 2 },
    { pregunta: "¿Cuál conducta corresponde a categoría B?", opciones: ["Competencias ilegales", "Placas falsas", "No usar dispositivo de seguridad para menores", "Exceso de velocidad extremo"], correcta: 2 },
    { pregunta: "El uso del teléfono celular mientras se conduce genera:", opciones: ["Advertencia verbal", "6 puntos en la licencia", "4 puntos en la licencia", "Suspensión inmediata sin proceso"], correcta: 2 },
    { pregunta: "Conducir a velocidades extremadamente altas puede considerarse:", opciones: ["Falta leve", "Conducción temeraria", "Error administrativo", "Infracción sin puntos"], correcta: 1 },
    { pregunta: "La conducción temeraria puede generar:", opciones: ["Solo multa económica", "Solo curso obligatorio", "Arresto inmediato", "Advertencia sin registro"], correcta: 2 },
    { pregunta: "Participar en competencias ilegales en la vía pública constituye:", opciones: ["Infracción categoría B", "Conducción temeraria", "Conducción preventiva", "Falta sin sanción"], correcta: 1 },
    { pregunta: "Si una persona acumula todos los puntos permitidos en su licencia:", opciones: ["Se suspende el derecho a conducir", "Se se le elimina la multa", "Debe pagar doble marchamo", "Solo recibe advertencia"], correcta: 0 },
    { pregunta: "Para reducir puntos acumulados, una opción es:", opciones: ["Cambiar de vehículo", "No pagar la multa", "Realizar curso de educación vial", "Presentar recurso automático"], correcta: 2 },
    { pregunta: "Si una persona reincide en pérdida total de puntos:", opciones: ["La suspensión puede ser más prolongada", "Se se le eliminan automáticamente", "No hay consecuencia adicional", "Solo paga multa económica"], correcta: 0 },
    { pregunta: "“Ceder el paso” significa:", opciones: ["Acelerar primero", "Detenerse siempre", "Ignorar señalización", "Permitir prioridad a quien corresponde"], correcta: 3 },
    { pregunta: "Una sanción administrativa puede incluir:", opciones: ["Pena de prisión", "Multa o suspensión de licencia", "Arresto inmediato", "Detención de 96 horas"], correcta: 1 },
    { pregunta: "Una sanción penal puede incluir:", opciones: ["Trabajo comunitario voluntario", "Multa leve", "Cárcel", "Advertencia escrita"], correcta: 2 },
    { pregunta: "No ceder el paso a peatones es:", opciones: ["Conducta permitida en zona urbana", "Solo falta moral", "Conducta de riesgo sancionable", "Recomendación opcional"], correcta: 2 },
    { pregunta: "Alterar o falsificar placas del vehículo constituye:", opciones: ["Falta sin puntos", "Advertencia administrativa", "Conducta de alto riesgo sancionable", "Infracción sin multa"], correcta: 2 },
    { pregunta: "Conducir bajo efectos del alcohol afecta principalmente:", opciones: ["Reflejos y capacidad de decisión", "Solo la velocidad", "Solo la vista", "Solo la audición"], correcta: 0 },
    { pregunta: "El sistema de puntos tiene como finalidad:", opciones: ["Castigar económicamente", "Quitar licencias permanentemente", "Aumentar multas", "Corregir conductas del conductor"], correcta: 3 },
    { pregunta: "En caso de recibir una boleta, el conductor puede:", opciones: ["Ignorarla", "Pagarla o impugnarla conforme al procedimiento legal", "Romperla", "Transferirla a otra persona"], correcta: 1 },
    { pregunta: "Un conductor es detenido por circular con placas alteradas. Esta conducta se clasifica como:", opciones: ["Infracción sin puntos", "Infracción categoría B", "Advertencia verbal", "Conducta de alto riesgo (categoría A)"], correcta: 3 },
    { pregunta: "Un conductor no respeta una señal de alto. Esta conducta genera:", opciones: ["6 puntos", "4 puntos", "No genera puntos", "Suspensión inmediata automática"], correcta: 1 },
    { pregunta: "Conducir bajo influencia del alcohol puede generar:", opciones: ["Solo multa económica", "Proceso penal y posible detención", "Multa y puntos", "Solo curso obligatorio"], correcta: 1 },
    { pregunta: "Si un conductor participa en competencias ilegales en la vía pública, puede enfrentar:", opciones: ["Arresto inmediato y proceso judicial", "Multa leve", "Solo suspensión temporal", "Solo acumulación de puntos"], correcta: 0 },
    { pregunta: "El sistema de puntos en la licencia busca principalmente:", opciones: ["Incrementar sanciones económicas", "Quitar licencias sin previo aviso", "Controlar y corregir conductas peligrosas", "Sancionar únicamente a conductores novatos"], correcta: 2 },
    { pregunta: "Un conductor acumula el máximo de puntos permitidos. ¿Qué ocurre?", opciones: ["Se suspende su derecho a conducir", "Recibe advertencia escrita", "Debe pagar doble multa", "Pierde el marchamo"], correcta: 0 },
    { pregunta: "Para recuperar puntos acumulados, el conductor puede:", opciones: ["Ignorar la infracción", "Realizar curso de educación vial o trabajo comunitario", "Renovar la licencia inmediatamente", "Cambiar de categoría de licencia"], correcta: 1 },
    { pregunta: "Si un conductor reincide y vuelve a perder todos los puntos, la consecuencia es:", opciones: ["Eliminación automática de puntos", "Reducción de multa", "Suspensión más prolongada", "Advertencia sin registro"], correcta: 2 },
    { pregunta: "No usar dispositivos de seguridad para menores constituye:", opciones: ["Categoría B", "Categoría A", "Falta sin puntos", "Sanción penal inmediata"], correcta: 0 },
    { pregunta: "El uso del teléfono celular mientras se conduce se clasifica como:", opciones: ["Conducción temeraria", "Infracción categoría B", "Infracción sin puntos", "Falta leve sin sanción"], correcta: 1 },
    { pregunta: "Un conductor que no usa luces reglamentarias puede recibir:", opciones: ["4 puntos en su licencia", "6 puntos en su licencia", "Solo advertencia", "Arresto inmediato"], correcta: 0 },
    { pregunta: "La conducción temeraria puede implicar detención de hasta:", opciones: ["24 horas", "48 horas", "72 horas", "96 horas"], correcta: 3 },
    { pregunta: "Conducir a velocidades extremadamente altas se considera:", opciones: ["Infracción leve", "Conducción temeraria", "Conducción preventiva", "Error administrativo"], correcta: 1 },
    { pregunta: "Una sanción administrativa puede incluir:", opciones: ["Pena de prisión", "Arresto inmediato", "Multa o suspensión de licencia", "Cárcel automática"], correcta: 2 },
    { pregunta: "Una sanción penal puede implicar:", opciones: ["Trabajo comunitario opcional", "Pena de prisión", "Multa leve sin registro", "Descuento de puntos"], correcta: 1 },
    { pregunta: "Si un conductor considera injusta una boleta de tránsito, puede:", opciones: ["Impugnarla siguiendo el procedimiento legal", "Ignorarla", "Transferirla a otra persona", "Romperla"], correcta: 0 },
    { pregunta: "Ceder el paso significa:", opciones: ["Acelerar para pasar primero", "Permitir prioridad al usuario correspondiente", "Detenerse siempre, aunque no sea necesario", "Ignorar la señalización"], correcta: 1 },
    { pregunta: "No ceder el paso a peatones constituye:", opciones: ["Conducta permitida", "Falta moral sin multa", "Conducta de riesgo sancionable", "Solo recomendación"], correcta: 2 },
    { pregunta: "Permitir exceso de pasajeros en el vehículo:", opciones: ["Es conducta de riesgo", "Es práctica común sin sanción", "Solo aplica a autobuses", "Es permitido en trayectos cortos"], correcta: 0 },
    { pregunta: "Conducir con exceso de carga puede:", opciones: ["Mejorar estabilidad", "No tener consecuencias", "Generar sanción y riesgo vial", "Solo afectar el consumo"], correcta: 2 },
    { pregunta: "Alterar dispositivos de seguridad ferroviaria es:", opciones: ["Falta administrativa leve", "Solo advertencia", "Conducta de alto riesgo", "Acción sin consecuencias"], correcta: 2 },
    { pregunta: "Las sanciones penales pueden aplicarse cuando:", opciones: ["Se estaciona mal", "Se olvida el cinturón", "Hay conducción temeraria", "Se usa direccional incorrectamente"], correcta: 2 },
    { pregunta: "El sistema de puntos se aplica cuando:", opciones: ["Se cometen infracciones que así lo establecen", "Se paga marchamo tarde", "Se cambia de vehículo", "Se renueva licencia"], correcta: 0 },
    { pregunta: "El objetivo principal de las normas de tránsito es:", opciones: ["Recaudar dinero", "Limitar el uso del vehículo", "Proteger la vida y la seguridad vial", "Aumentar la cantidad de multas"], correcta: 2 },
    { pregunta: "Si una persona pierde el derecho a conducir por acumulación de puntos:", opciones: ["Puede seguir conduciendo si paga multa", "Debe cumplir el periodo de suspensión", "Solo pierde puntos sin efecto real", "Puede delegar su licencia"], correcta: 1 },
    { pregunta: "El incumplimiento de normas puede generar consecuencias:", opciones: ["Solo económicas", "Solo administrativas", "Económicas, administrativas y penales", "Solo penales"], correcta: 2 },
    { pregunta: "El compromiso individual del conductor es fundamental porque:", opciones: ["Las normas no son obligatorias", "Solo la policía controla la seguridad", "La seguridad vial depende del comportamiento de cada persona", "El sistema elimina errores automáticamente"], correcta: 2 },
    { pregunta: "Una infracción categoría A implica mayor gravedad que categoría B porque:", opciones: ["Acumula menos puntos", "Representa conductas de alto riesgo", "No genera multa", "Solo aplica a conductores profesionales"], correcta: 1 },
    { pregunta: "El arresto inmediato puede aplicarse en casos de:", opciones: ["Estacionamiento incorrecto leve", "No usar direccional", "Uso de luces bajas", "Conducción temeraria"], correcta: 3 },
    { pregunta: "Las normas de tránsito existen principalmente para:", opciones: ["Castigar conductores", "Regular la movilidad y proteger vidas", "Aumentar sanciones", "Favorecer a ciertos usuarios"], correcta: 1 }
];
